/**
 * AUTO-GENERATED loader (regenerated to match files on disk).
 * Loads ONLY the lightweight original categories (characters, vfx,
 * environment). Heavy new folders (backdrops, props, enemies, etc.)
 * are loaded selectively elsewhere to avoid blowing the texture budget.
 */
export const IMPORTED_KEYS = { characters: [], vfx: [], environment: [] };
export const ImportedAssets = {
  preload(scene) {
    scene.load.image('imp_animation6', 'assets/imported/characters/Animation6.png');
    IMPORTED_KEYS.characters.push('imp_animation6');
    scene.load.spritesheet('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px_1', 'assets/imported/characters/corrupted-tree-sentenel_run_top-down_6col_3row_256px (1).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px_1');
    scene.load.spritesheet('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px', 'assets/imported/characters/corrupted-tree-sentenel_run_top-down_6col_3row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px');
    scene.load.spritesheet('imp_corrupted_tree_sentenel_run_top_down_7col_3row_256px', 'assets/imported/characters/corrupted-tree-sentenel_run_top-down_7col_3row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_corrupted_tree_sentenel_run_top_down_7col_3row_256px');
    scene.load.spritesheet('imp_corruptedtreetitan_walk_top_down_5col_7row_256px_2', 'assets/imported/characters/corruptedtreetitan_walk_top-down_5col_7row_256px (2).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_corruptedtreetitan_walk_top_down_5col_7row_256px_2');
    scene.load.spritesheet('imp_corruptedtreetitan_walk_top_down_5col_7row_256px', 'assets/imported/characters/corruptedtreetitan_walk_top-down_5col_7row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_corruptedtreetitan_walk_top_down_5col_7row_256px');
    scene.load.spritesheet('imp_druid_run_top_down_8col_3row_256px', 'assets/imported/characters/druid_run_top-down_8col_3row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_druid_run_top_down_8col_3row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_10row_256px', 'assets/imported/characters/sprite_everything_front_5col_10row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_10row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_11row_256px', 'assets/imported/characters/sprite_everything_front_5col_11row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_11row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_12row_256px', 'assets/imported/characters/sprite_everything_front_5col_12row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_12row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_3row_256px', 'assets/imported/characters/sprite_everything_front_5col_3row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_3row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_8row_256px', 'assets/imported/characters/sprite_everything_front_5col_8row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_8row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_6col_3row_256px_1', 'assets/imported/characters/sprite_everything_front_6col_3row_256px (1).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_6col_3row_256px_1');
    scene.load.spritesheet('imp_sprite_everything_front_6col_3row_256px_2', 'assets/imported/characters/sprite_everything_front_6col_3row_256px (2).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_6col_3row_256px_2');
    scene.load.spritesheet('imp_sprite_powerfulswordattack_front_7col_9row_256px', 'assets/imported/characters/sprite_powerfulswordattack_front_7col_9row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_powerfulswordattack_front_7col_9row_256px');
    scene.load.spritesheet('imp_sprite_run_front_16col_2row_256px', 'assets/imported/characters/sprite_run_front_16col_2row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_16col_2row_256px');
    scene.load.spritesheet('imp_sprite_run_front_6col_3row_256px', 'assets/imported/characters/sprite_run_front_6col_3row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_6col_3row_256px');
    scene.load.spritesheet('imp_sprite_run_front_7col_4row_64px', 'assets/imported/characters/sprite_run_front_7col_4row_64px.png', { frameWidth: 64, frameHeight: 64 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_7col_4row_64px');
    scene.load.spritesheet('imp_sprite_run_front_8col_2row_256px_1', 'assets/imported/characters/sprite_run_front_8col_2row_256px (1).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_2row_256px_1');
    scene.load.spritesheet('imp_sprite_run_front_8col_2row_256px_2', 'assets/imported/characters/sprite_run_front_8col_2row_256px (2).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_2row_256px_2');
    scene.load.spritesheet('imp_sprite_run_front_8col_2row_256px', 'assets/imported/characters/sprite_run_front_8col_2row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_2row_256px');
    scene.load.spritesheet('imp_sprite_run_front_8col_3row_256px', 'assets/imported/characters/sprite_run_front_8col_3row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_3row_256px');
    scene.load.spritesheet('imp_sprite_run_front_9col_2row_256px', 'assets/imported/characters/sprite_run_front_9col_2row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_9col_2row_256px');
    scene.load.spritesheet('imp_sprite_walk_front_6col_5row_256px', 'assets/imported/characters/sprite_walk_front_6col_5row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_sprite_walk_front_6col_5row_256px');
    scene.load.spritesheet('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px_1', 'assets/imported/characters/tree-titan_treetitantakedamagedie_top-down_5col_6row_256px (1).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px_1');
    scene.load.spritesheet('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px', 'assets/imported/characters/tree-titan_treetitantakedamagedie_top-down_5col_6row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px');
    scene.load.spritesheet('imp_tree_idle_top_down_10col_10row_256px', 'assets/imported/characters/tree_idle_top-down_10col_10row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_10col_10row_256px');
    scene.load.spritesheet('imp_tree_idle_top_down_8col_13row_256px_1', 'assets/imported/characters/tree_idle_top-down_8col_13row_256px (1).png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_8col_13row_256px_1');
    scene.load.spritesheet('imp_tree_idle_top_down_8col_13row_256px', 'assets/imported/characters/tree_idle_top-down_8col_13row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_8col_13row_256px');
    scene.load.spritesheet('imp_tree_idle_top_down_8col_3row_256px', 'assets/imported/characters/tree_idle_top-down_8col_3row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_8col_3row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanswordattack_top_down_14col_5row_256px', 'assets/imported/characters/treetitan_treetitanswordattack_top-down_14col_5row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanswordattack_top_down_14col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanswordattack_top_down_6col_5row_256px', 'assets/imported/characters/treetitan_treetitanswordattack_top-down_6col_5row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanswordattack_top_down_6col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanswordattack_top_down_7col_5row_256px', 'assets/imported/characters/treetitan_treetitanswordattack_top-down_7col_5row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanswordattack_top_down_7col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanwalk_top_down_10col_5row_256px', 'assets/imported/characters/treetitan_treetitanwalk_top-down_10col_5row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanwalk_top_down_10col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanwalk_top_down_6col_10row_256px', 'assets/imported/characters/treetitan_treetitanwalk_top-down_6col_10row_256px.png', { frameWidth: 256, frameHeight: 256 });
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanwalk_top_down_6col_10row_256px');
    scene.load.image('imp_vfx_cure1', 'assets/imported/vfx/Cure1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure1');
    scene.load.image('imp_vfx_cure2', 'assets/imported/vfx/Cure2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure2');
    scene.load.image('imp_vfx_cure3', 'assets/imported/vfx/Cure3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure3');
    scene.load.image('imp_vfx_cure4', 'assets/imported/vfx/Cure4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure4');
    scene.load.image('imp_vfx_curse', 'assets/imported/vfx/Curse.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_curse');
    scene.load.image('imp_vfx_darkness1', 'assets/imported/vfx/Darkness1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness1');
    scene.load.image('imp_vfx_darkness3', 'assets/imported/vfx/Darkness3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness3');
    scene.load.image('imp_vfx_darkness4', 'assets/imported/vfx/Darkness4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness4');
    scene.load.image('imp_vfx_darkness5', 'assets/imported/vfx/Darkness5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness5');
    scene.load.image('imp_vfx_earth1', 'assets/imported/vfx/Earth1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth1');
    scene.load.image('imp_vfx_earth2', 'assets/imported/vfx/Earth2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth2');
    scene.load.image('imp_vfx_earth3', 'assets/imported/vfx/Earth3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth3');
    scene.load.image('imp_vfx_earth5', 'assets/imported/vfx/Earth5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth5');
    scene.load.image('imp_vfx_explosion1', 'assets/imported/vfx/Explosion1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_explosion1');
    scene.load.image('imp_vfx_explosion2', 'assets/imported/vfx/Explosion2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_explosion2');
    scene.load.image('imp_vfx_fire1', 'assets/imported/vfx/Fire1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_fire1');
    scene.load.image('imp_vfx_fire2', 'assets/imported/vfx/Fire2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_fire2');
    scene.load.image('imp_vfx_fire3', 'assets/imported/vfx/Fire3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_fire3');
    scene.load.image('imp_vfx_gun1', 'assets/imported/vfx/Gun1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_gun1');
    scene.load.image('imp_vfx_gun2', 'assets/imported/vfx/Gun2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_gun2');
    scene.load.image('imp_vfx_gun3', 'assets/imported/vfx/Gun3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_gun3');
    scene.load.image('imp_vfx_hit2', 'assets/imported/vfx/Hit2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hit2');
    scene.load.image('imp_vfx_hitfire', 'assets/imported/vfx/HitFire.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitfire');
    scene.load.image('imp_vfx_hitice', 'assets/imported/vfx/HitIce.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitice');
    scene.load.image('imp_vfx_hitphoton', 'assets/imported/vfx/HitPhoton.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitphoton');
    scene.load.image('imp_vfx_hitspecial1', 'assets/imported/vfx/HitSpecial1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitspecial1');
    scene.load.image('imp_vfx_hitspecial2', 'assets/imported/vfx/HitSpecial2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitspecial2');
    scene.load.image('imp_vfx_holy1', 'assets/imported/vfx/Holy1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy1');
    scene.load.image('imp_vfx_holy2', 'assets/imported/vfx/Holy2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy2');
    scene.load.image('imp_vfx_holy3', 'assets/imported/vfx/Holy3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy3');
    scene.load.image('imp_vfx_holy4', 'assets/imported/vfx/Holy4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy4');
    scene.load.image('imp_vfx_holy5', 'assets/imported/vfx/Holy5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy5');
    scene.load.image('imp_vfx_howl', 'assets/imported/vfx/Howl.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_howl');
    scene.load.image('imp_vfx_ice2', 'assets/imported/vfx/Ice2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice2');
    scene.load.image('imp_vfx_ice3', 'assets/imported/vfx/Ice3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice3');
    scene.load.image('imp_vfx_ice4', 'assets/imported/vfx/Ice4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice4');
    scene.load.image('imp_vfx_ice5', 'assets/imported/vfx/Ice5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice5');
    scene.load.image('imp_vfx_laser1', 'assets/imported/vfx/Laser1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_laser1');
    scene.load.image('imp_vfx_light_balls_tree1', 'assets/imported/vfx/Light_balls_tree1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_light_balls_tree1');
    scene.load.image('imp_vfx_light_balls_tree2', 'assets/imported/vfx/Light_balls_tree2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_light_balls_tree2');
    scene.load.image('imp_vfx_light_balls_tree3', 'assets/imported/vfx/Light_balls_tree3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_light_balls_tree3');
    scene.load.image('imp_vfx_slashspecial1', 'assets/imported/vfx/SlashSpecial1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashspecial1');
    scene.load.image('imp_vfx_slashspecial2', 'assets/imported/vfx/SlashSpecial2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashspecial2');
    scene.load.image('imp_vfx_slashspecial3', 'assets/imported/vfx/SlashSpecial3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashspecial3');
    scene.load.image('imp_vfx_slashthunder', 'assets/imported/vfx/SlashThunder.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashthunder');
    scene.load.image('imp_vfx_song', 'assets/imported/vfx/Song.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_song');
    scene.load.image('imp_vfx_sonic', 'assets/imported/vfx/Sonic.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_sonic');
    scene.load.image('imp_vfx_special1', 'assets/imported/vfx/Special1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_special1');
    scene.load.image('imp_vfx_special2', 'assets/imported/vfx/Special2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_special2');
    scene.load.image('imp_vfx_special3', 'assets/imported/vfx/Special3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_special3');
    scene.load.image('imp_vfx_statechaos', 'assets/imported/vfx/StateChaos.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statechaos');
    scene.load.image('imp_vfx_statedark', 'assets/imported/vfx/StateDark.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedark');
    scene.load.image('imp_vfx_statedeath', 'assets/imported/vfx/StateDeath.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedeath');
    scene.load.image('imp_vfx_statedown1', 'assets/imported/vfx/StateDown1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedown1');
    scene.load.image('imp_vfx_statedown2', 'assets/imported/vfx/StateDown2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedown2');
    scene.load.image('imp_vfx_statedown3', 'assets/imported/vfx/StateDown3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedown3');
    scene.load.image('imp_vfx_stateparalys', 'assets/imported/vfx/StateParalys.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stateparalys');
    scene.load.image('imp_vfx_statepoison', 'assets/imported/vfx/StatePoison.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statepoison');
    scene.load.image('imp_vfx_statesilent', 'assets/imported/vfx/StateSilent.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statesilent');
    scene.load.image('imp_vfx_statesleep', 'assets/imported/vfx/StateSleep.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statesleep');
    scene.load.image('imp_vfx_stateup1', 'assets/imported/vfx/StateUp1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stateup1');
    scene.load.image('imp_vfx_stateup2', 'assets/imported/vfx/StateUp2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stateup2');
    scene.load.image('imp_vfx_stick', 'assets/imported/vfx/Stick.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stick');
    scene.load.image('imp_vfx_stickphoton', 'assets/imported/vfx/StickPhoton.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickphoton');
    scene.load.image('imp_vfx_stickspecial1', 'assets/imported/vfx/StickSpecial1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickspecial1');
    scene.load.image('imp_vfx_stickspecial2', 'assets/imported/vfx/StickSpecial2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickspecial2');
    scene.load.image('imp_vfx_stickspecial3', 'assets/imported/vfx/StickSpecial3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickspecial3');
    scene.load.image('imp_vfx_thunder1', 'assets/imported/vfx/Thunder1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder1');
    scene.load.image('imp_vfx_thunder2', 'assets/imported/vfx/Thunder2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder2');
    scene.load.image('imp_vfx_thunder3', 'assets/imported/vfx/Thunder3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder3');
    scene.load.image('imp_vfx_thunder4', 'assets/imported/vfx/Thunder4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder4');
    scene.load.image('imp_vfx_thunder5', 'assets/imported/vfx/Thunder5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder5');
    scene.load.image('imp_env_anchor_shadow1', 'assets/imported/environment/Anchor_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_anchor_shadow1');
    scene.load.image('imp_env_anchor_shadow2', 'assets/imported/environment/Anchor_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_anchor_shadow2');
    scene.load.image('imp_env_anchor_shadow3', 'assets/imported/environment/Anchor_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_anchor_shadow3');
    scene.load.image('imp_env_beige_violet_coral1_shadow1', 'assets/imported/environment/Beige-violet_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral1_shadow1');
    scene.load.image('imp_env_beige_violet_coral1_shadow2', 'assets/imported/environment/Beige-violet_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral1_shadow2');
    scene.load.image('imp_env_beige_violet_coral1_shadow3', 'assets/imported/environment/Beige-violet_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral1_shadow3');
    scene.load.image('imp_env_beige_violet_coral2_shadow1', 'assets/imported/environment/Beige-violet_coral2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral2_shadow1');
    scene.load.image('imp_env_beige_violet_coral2_shadow2', 'assets/imported/environment/Beige-violet_coral2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral2_shadow2');
    scene.load.image('imp_env_beige_violet_coral2_shadow3', 'assets/imported/environment/Beige-violet_coral2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral2_shadow3');
    scene.load.image('imp_env_blue_beige_coral1_shadow1', 'assets/imported/environment/Blue-beige_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_beige_coral1_shadow1');
    scene.load.image('imp_env_blue_beige_coral1_shadow2', 'assets/imported/environment/Blue-beige_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_beige_coral1_shadow2');
    scene.load.image('imp_env_blue_beige_coral1_shadow3', 'assets/imported/environment/Blue-beige_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_beige_coral1_shadow3');
    scene.load.image('imp_env_blue_coral1_shadow1', 'assets/imported/environment/Blue_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_coral1_shadow1');
    scene.load.image('imp_env_blue_coral1_shadow2', 'assets/imported/environment/Blue_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_coral1_shadow2');
    scene.load.image('imp_env_blue_coral1_shadow3', 'assets/imported/environment/Blue_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_coral1_shadow3');
    scene.load.image('imp_env_brown_white_shell1_shadow1', 'assets/imported/environment/Brown-white_shell1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell1_shadow1');
    scene.load.image('imp_env_brown_white_shell1_shadow2', 'assets/imported/environment/Brown-white_shell1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell1_shadow2');
    scene.load.image('imp_env_brown_white_shell1_shadow3', 'assets/imported/environment/Brown-white_shell1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell1_shadow3');
    scene.load.image('imp_env_brown_white_shell2_shadow1', 'assets/imported/environment/Brown-white_shell2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell2_shadow1');
    scene.load.image('imp_env_brown_white_shell2_shadow2', 'assets/imported/environment/Brown-white_shell2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell2_shadow2');
    scene.load.image('imp_env_brown_white_shell2_shadow3', 'assets/imported/environment/Brown-white_shell2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell2_shadow3');
    scene.load.image('imp_env_crab_shadow1', 'assets/imported/environment/Crab_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_crab_shadow1');
    scene.load.image('imp_env_crab_shadow2', 'assets/imported/environment/Crab_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_crab_shadow2');
    scene.load.image('imp_env_crab_shadow3', 'assets/imported/environment/Crab_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_crab_shadow3');
    scene.load.image('imp_env_dragon_bones_shadow1', 'assets/imported/environment/Dragon_bones_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_dragon_bones_shadow1');
    scene.load.image('imp_env_dragon_bones_shadow2', 'assets/imported/environment/Dragon_bones_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_dragon_bones_shadow2');
    scene.load.image('imp_env_dragon_bones_shadow3', 'assets/imported/environment/Dragon_bones_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_dragon_bones_shadow3');
    scene.load.image('imp_env_gray_red_coral1_shadow1', 'assets/imported/environment/Gray-red_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral1_shadow1');
    scene.load.image('imp_env_gray_red_coral1_shadow2', 'assets/imported/environment/Gray-red_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral1_shadow2');
    scene.load.image('imp_env_gray_red_coral1_shadow3', 'assets/imported/environment/Gray-red_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral1_shadow3');
    scene.load.image('imp_env_gray_red_coral2_shadow1', 'assets/imported/environment/Gray-red_coral2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral2_shadow1');
    scene.load.image('imp_env_gray_red_coral2_shadow2', 'assets/imported/environment/Gray-red_coral2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral2_shadow2');
    scene.load.image('imp_env_gray_red_coral2_shadow3', 'assets/imported/environment/Gray-red_coral2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral2_shadow3');
    scene.load.image('imp_env_mermaid_house_shadow1', 'assets/imported/environment/Mermaid_house_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_mermaid_house_shadow1');
    scene.load.image('imp_env_mermaid_house_shadow2', 'assets/imported/environment/Mermaid_house_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_mermaid_house_shadow2');
    scene.load.image('imp_env_mermaid_house_shadow3', 'assets/imported/environment/Mermaid_house_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_mermaid_house_shadow3');
    scene.load.image('imp_env_monster_fish_bones_shadow1', 'assets/imported/environment/Monster_fish_bones_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_monster_fish_bones_shadow1');
    scene.load.image('imp_env_monster_fish_bones_shadow2', 'assets/imported/environment/Monster_fish_bones_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_monster_fish_bones_shadow2');
    scene.load.image('imp_env_monster_fish_bones_shadow3', 'assets/imported/environment/Monster_fish_bones_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_monster_fish_bones_shadow3');
    scene.load.image('imp_env_pearl_sea_shell1_shadow1', 'assets/imported/environment/Pearl_sea_shell1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_pearl_sea_shell1_shadow1');
    scene.load.image('imp_env_pearl_sea_shell1_shadow2', 'assets/imported/environment/Pearl_sea_shell1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_pearl_sea_shell1_shadow2');
    scene.load.image('imp_env_pearl_sea_shell1_shadow3', 'assets/imported/environment/Pearl_sea_shell1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_pearl_sea_shell1_shadow3');
    scene.load.image('imp_env_riff1_shadow1', 'assets/imported/environment/Riff1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff1_shadow1');
    scene.load.image('imp_env_riff1_shadow2', 'assets/imported/environment/Riff1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff1_shadow2');
    scene.load.image('imp_env_riff1_shadow3', 'assets/imported/environment/Riff1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff1_shadow3');
    scene.load.image('imp_env_riff2_shadow1', 'assets/imported/environment/Riff2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff2_shadow1');
    scene.load.image('imp_env_riff2_shadow2', 'assets/imported/environment/Riff2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff2_shadow2');
    scene.load.image('imp_env_riff2_shadow3', 'assets/imported/environment/Riff2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff2_shadow3');
    scene.load.image('imp_env_riff3_shadow1', 'assets/imported/environment/Riff3_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff3_shadow1');
    scene.load.image('imp_env_riff3_shadow2', 'assets/imported/environment/Riff3_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff3_shadow2');
    scene.load.image('imp_env_riff3_shadow3', 'assets/imported/environment/Riff3_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff3_shadow3');
    scene.load.image('imp_env_riff4_shadow1', 'assets/imported/environment/Riff4_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff4_shadow1');
    scene.load.image('imp_env_riff4_shadow2', 'assets/imported/environment/Riff4_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff4_shadow2');
    scene.load.image('imp_env_riff4_shadow3', 'assets/imported/environment/Riff4_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff4_shadow3');
    scene.load.image('imp_env_sea_insect_shadow1', 'assets/imported/environment/Sea_insect_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_insect_shadow1');
    scene.load.image('imp_env_sea_insect_shadow2', 'assets/imported/environment/Sea_insect_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_insect_shadow2');
    scene.load.image('imp_env_sea_insect_shadow3', 'assets/imported/environment/Sea_insect_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_insect_shadow3');
    scene.load.image('imp_env_sea_urchin1_shadow1', 'assets/imported/environment/Sea_urchin1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin1_shadow1');
    scene.load.image('imp_env_sea_urchin1_shadow2', 'assets/imported/environment/Sea_urchin1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin1_shadow2');
    scene.load.image('imp_env_sea_urchin1_shadow3', 'assets/imported/environment/Sea_urchin1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin1_shadow3');
    scene.load.image('imp_env_sea_urchin2_shadow1', 'assets/imported/environment/Sea_urchin2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin2_shadow1');
    scene.load.image('imp_env_sea_urchin2_shadow2', 'assets/imported/environment/Sea_urchin2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin2_shadow2');
    scene.load.image('imp_env_sea_urchin2_shadow3', 'assets/imported/environment/Sea_urchin2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin2_shadow3');
    scene.load.image('imp_env_ship1_shadow1', 'assets/imported/environment/Ship1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_ship1_shadow1');
    scene.load.image('imp_env_ship1_shadow2', 'assets/imported/environment/Ship1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_ship1_shadow2');
    scene.load.image('imp_env_ship1_shadow3', 'assets/imported/environment/Ship1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_ship1_shadow3');
    scene.load.image('imp_env_ship2_shadow1', 'assets/imported/environment/Ship2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_ship2_shadow1');
    scene.load.image('imp_env_ship2_shadow2', 'assets/imported/environment/Ship2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_ship2_shadow2');
    scene.load.image('imp_env_ship2_shadow3', 'assets/imported/environment/Ship2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_ship2_shadow3');
    scene.load.image('imp_env_starfish1_shadow1', 'assets/imported/environment/Starfish1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish1_shadow1');
    scene.load.image('imp_env_starfish1_shadow2', 'assets/imported/environment/Starfish1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish1_shadow2');
    scene.load.image('imp_env_starfish1_shadow3', 'assets/imported/environment/Starfish1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish1_shadow3');
    scene.load.image('imp_env_starfish2_shadow1', 'assets/imported/environment/Starfish2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish2_shadow1');
    scene.load.image('imp_env_starfish2_shadow2', 'assets/imported/environment/Starfish2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish2_shadow2');
    scene.load.image('imp_env_starfish2_shadow3', 'assets/imported/environment/Starfish2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish2_shadow3');
    scene.load.image('imp_env_statue1_shadow1', 'assets/imported/environment/Statue1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_statue1_shadow1');
    scene.load.image('imp_env_statue1_shadow2', 'assets/imported/environment/Statue1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_statue1_shadow2');
    scene.load.image('imp_env_statue1_shadow3', 'assets/imported/environment/Statue1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_statue1_shadow3');
    scene.load.image('imp_env_statue2_shadow1', 'assets/imported/environment/Statue2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_statue2_shadow1');
    scene.load.image('imp_env_statue2_shadow2', 'assets/imported/environment/Statue2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_statue2_shadow2');
    scene.load.image('imp_env_statue2_shadow3', 'assets/imported/environment/Statue2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_statue2_shadow3');
    scene.load.image('imp_env_steering_wheel_shadow1', 'assets/imported/environment/Steering_wheel_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_steering_wheel_shadow1');
    scene.load.image('imp_env_steering_wheel_shadow2', 'assets/imported/environment/Steering_wheel_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_steering_wheel_shadow2');
    scene.load.image('imp_env_steering_wheel_shadow3', 'assets/imported/environment/Steering_wheel_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_steering_wheel_shadow3');
    scene.load.image('imp_env_turtle_shell_shadow1', 'assets/imported/environment/Turtle_shell_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_turtle_shell_shadow1');
    scene.load.image('imp_env_turtle_shell_shadow2', 'assets/imported/environment/Turtle_shell_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_turtle_shell_shadow2');
    scene.load.image('imp_env_turtle_shell_shadow3', 'assets/imported/environment/Turtle_shell_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_turtle_shell_shadow3');
    scene.load.image('imp_env_violet_pink_coral1_shadow1', 'assets/imported/environment/Violet-pink_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral1_shadow1');
    scene.load.image('imp_env_violet_pink_coral1_shadow2', 'assets/imported/environment/Violet-pink_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral1_shadow2');
    scene.load.image('imp_env_violet_pink_coral1_shadow3', 'assets/imported/environment/Violet-pink_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral1_shadow3');
    scene.load.image('imp_env_violet_pink_coral2_shadow1', 'assets/imported/environment/Violet-pink_coral2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral2_shadow1');
    scene.load.image('imp_env_violet_pink_coral2_shadow2', 'assets/imported/environment/Violet-pink_coral2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral2_shadow2');
    scene.load.image('imp_env_violet_pink_coral2_shadow3', 'assets/imported/environment/Violet-pink_coral2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral2_shadow3');
    scene.load.image('imp_env_violet_pink_coral3_shadow1', 'assets/imported/environment/Violet-pink_coral3_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral3_shadow1');
    scene.load.image('imp_env_violet_pink_coral3_shadow2', 'assets/imported/environment/Violet-pink_coral3_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral3_shadow2');
    scene.load.image('imp_env_violet_pink_coral3_shadow3', 'assets/imported/environment/Violet-pink_coral3_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral3_shadow3');
    scene.load.image('imp_env_yellow_white_gray_shell1_shadow1', 'assets/imported/environment/Yellow-white-gray_shell1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_white_gray_shell1_shadow1');
    scene.load.image('imp_env_yellow_white_gray_shell1_shadow2', 'assets/imported/environment/Yellow-white-gray_shell1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_white_gray_shell1_shadow2');
    scene.load.image('imp_env_yellow_white_gray_shell1_shadow3', 'assets/imported/environment/Yellow-white-gray_shell1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_white_gray_shell1_shadow3');
    scene.load.image('imp_env_building_1_10', 'assets/imported/environment/building_1 (10).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_10');
    scene.load.image('imp_env_building_1_11', 'assets/imported/environment/building_1 (11).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_11');
    scene.load.image('imp_env_building_1_12', 'assets/imported/environment/building_1 (12).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_12');
    scene.load.image('imp_env_building_1_13', 'assets/imported/environment/building_1 (13).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_13');
    scene.load.image('imp_env_building_1_14', 'assets/imported/environment/building_1 (14).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_14');
    scene.load.image('imp_env_building_1_15', 'assets/imported/environment/building_1 (15).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_15');
    scene.load.image('imp_env_building_1_16', 'assets/imported/environment/building_1 (16).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_16');
    scene.load.image('imp_env_building_1_2', 'assets/imported/environment/building_1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_2');
    scene.load.image('imp_env_building_1_3', 'assets/imported/environment/building_1 (3).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_3');
    scene.load.image('imp_env_building_1_4', 'assets/imported/environment/building_1 (4).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_4');
    scene.load.image('imp_env_building_1_5', 'assets/imported/environment/building_1 (5).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_5');
    scene.load.image('imp_env_building_1_6', 'assets/imported/environment/building_1 (6).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_6');
    scene.load.image('imp_env_building_1_7', 'assets/imported/environment/building_1 (7).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_7');
    scene.load.image('imp_env_building_1_8', 'assets/imported/environment/building_1 (8).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_8');
    scene.load.image('imp_env_building_1_9', 'assets/imported/environment/building_1 (9).png');
    IMPORTED_KEYS.environment.push('imp_env_building_1_9');
    scene.load.image('imp_env_building_1', 'assets/imported/environment/building_1.png');
    IMPORTED_KEYS.environment.push('imp_env_building_1');
    scene.load.image('imp_env_building_2', 'assets/imported/environment/building_2.png');
    IMPORTED_KEYS.environment.push('imp_env_building_2');
    scene.load.image('imp_env_building_3', 'assets/imported/environment/building_3.png');
    IMPORTED_KEYS.environment.push('imp_env_building_3');
    scene.load.image('imp_env_building_4', 'assets/imported/environment/building_4.png');
    IMPORTED_KEYS.environment.push('imp_env_building_4');
    scene.load.image('imp_env_building_5_2', 'assets/imported/environment/building_5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_building_5_2');
    scene.load.image('imp_env_building_5', 'assets/imported/environment/building_5.png');
    IMPORTED_KEYS.environment.push('imp_env_building_5');
    scene.load.image('imp_env_building_7', 'assets/imported/environment/building_7.png');
    IMPORTED_KEYS.environment.push('imp_env_building_7');
  }
};
