/**
 * AUTO-GENERATED loader for imported sprite sheets and assets.
 * Call ImportedAssets.preload(scene) from a Phaser scene's preload().
 * Texture keys are derived from filenames (sanitized to snake_case).
 */

export const IMPORTED_KEYS = {
  characters: [],
  vfx: [],
  environment: []
};

export const ImportedAssets = {
  preload(scene) {
    // ---- Character / enemy sprite sheets (frame dims parsed from filename) ----
    scene.load.image('imp_animation6', 'assets/imported/characters/Animation6.png');
    IMPORTED_KEYS.characters.push('imp_animation6');
    scene.load.spritesheet('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px_1', 'assets/imported/characters/corrupted-tree-sentenel_run_top-down_6col_3row_256px (1).png', { frameWidth: 256, frameHeight: 256 }); // 6x3
    IMPORTED_KEYS.characters.push('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px_1');
    scene.load.spritesheet('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px', 'assets/imported/characters/corrupted-tree-sentenel_run_top-down_6col_3row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 6x3
    IMPORTED_KEYS.characters.push('imp_corrupted_tree_sentenel_run_top_down_6col_3row_256px');
    scene.load.spritesheet('imp_corrupted_tree_sentenel_run_top_down_7col_3row_256px', 'assets/imported/characters/corrupted-tree-sentenel_run_top-down_7col_3row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 7x3
    IMPORTED_KEYS.characters.push('imp_corrupted_tree_sentenel_run_top_down_7col_3row_256px');
    scene.load.spritesheet('imp_corruptedtreetitan_walk_top_down_5col_7row_256px_2', 'assets/imported/characters/corruptedtreetitan_walk_top-down_5col_7row_256px (2).png', { frameWidth: 256, frameHeight: 256 }); // 5x7
    IMPORTED_KEYS.characters.push('imp_corruptedtreetitan_walk_top_down_5col_7row_256px_2');
    scene.load.spritesheet('imp_corruptedtreetitan_walk_top_down_5col_7row_256px', 'assets/imported/characters/corruptedtreetitan_walk_top-down_5col_7row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 5x7
    IMPORTED_KEYS.characters.push('imp_corruptedtreetitan_walk_top_down_5col_7row_256px');
    scene.load.spritesheet('imp_druid_run_top_down_8col_3row_256px', 'assets/imported/characters/druid_run_top-down_8col_3row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 8x3
    IMPORTED_KEYS.characters.push('imp_druid_run_top_down_8col_3row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_10row_256px', 'assets/imported/characters/sprite_everything_front_5col_10row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 5x10
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_10row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_11row_256px', 'assets/imported/characters/sprite_everything_front_5col_11row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 5x11
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_11row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_12row_256px', 'assets/imported/characters/sprite_everything_front_5col_12row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 5x12
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_12row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_3row_256px', 'assets/imported/characters/sprite_everything_front_5col_3row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 5x3
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_3row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_5col_8row_256px', 'assets/imported/characters/sprite_everything_front_5col_8row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 5x8
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_5col_8row_256px');
    scene.load.spritesheet('imp_sprite_everything_front_6col_3row_256px_1', 'assets/imported/characters/sprite_everything_front_6col_3row_256px (1).png', { frameWidth: 256, frameHeight: 256 }); // 6x3
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_6col_3row_256px_1');
    scene.load.spritesheet('imp_sprite_everything_front_6col_3row_256px_2', 'assets/imported/characters/sprite_everything_front_6col_3row_256px (2).png', { frameWidth: 256, frameHeight: 256 }); // 6x3
    IMPORTED_KEYS.characters.push('imp_sprite_everything_front_6col_3row_256px_2');
    scene.load.spritesheet('imp_sprite_powerfulswordattack_front_7col_9row_256px', 'assets/imported/characters/sprite_powerfulswordattack_front_7col_9row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 7x9
    IMPORTED_KEYS.characters.push('imp_sprite_powerfulswordattack_front_7col_9row_256px');
    scene.load.spritesheet('imp_sprite_run_front_16col_2row_256px', 'assets/imported/characters/sprite_run_front_16col_2row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 16x2
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_16col_2row_256px');
    scene.load.spritesheet('imp_sprite_run_front_6col_3row_256px', 'assets/imported/characters/sprite_run_front_6col_3row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 6x3
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_6col_3row_256px');
    scene.load.spritesheet('imp_sprite_run_front_7col_4row_64px', 'assets/imported/characters/sprite_run_front_7col_4row_64px.png', { frameWidth: 64, frameHeight: 64 }); // 7x4
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_7col_4row_64px');
    scene.load.spritesheet('imp_sprite_run_front_8col_2row_256px_1', 'assets/imported/characters/sprite_run_front_8col_2row_256px (1).png', { frameWidth: 256, frameHeight: 256 }); // 8x2
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_2row_256px_1');
    scene.load.spritesheet('imp_sprite_run_front_8col_2row_256px_2', 'assets/imported/characters/sprite_run_front_8col_2row_256px (2).png', { frameWidth: 256, frameHeight: 256 }); // 8x2
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_2row_256px_2');
    scene.load.spritesheet('imp_sprite_run_front_8col_2row_256px', 'assets/imported/characters/sprite_run_front_8col_2row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 8x2
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_2row_256px');
    scene.load.spritesheet('imp_sprite_run_front_8col_3row_256px', 'assets/imported/characters/sprite_run_front_8col_3row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 8x3
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_8col_3row_256px');
    scene.load.spritesheet('imp_sprite_run_front_9col_2row_256px', 'assets/imported/characters/sprite_run_front_9col_2row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 9x2
    IMPORTED_KEYS.characters.push('imp_sprite_run_front_9col_2row_256px');
    scene.load.spritesheet('imp_sprite_walk_front_6col_5row_256px', 'assets/imported/characters/sprite_walk_front_6col_5row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 6x5
    IMPORTED_KEYS.characters.push('imp_sprite_walk_front_6col_5row_256px');
    scene.load.spritesheet('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px_1', 'assets/imported/characters/tree-titan_treetitantakedamagedie_top-down_5col_6row_256px (1).png', { frameWidth: 256, frameHeight: 256 }); // 5x6
    IMPORTED_KEYS.characters.push('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px_1');
    scene.load.spritesheet('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px', 'assets/imported/characters/tree-titan_treetitantakedamagedie_top-down_5col_6row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 5x6
    IMPORTED_KEYS.characters.push('imp_tree_titan_treetitantakedamagedie_top_down_5col_6row_256px');
    scene.load.spritesheet('imp_tree_idle_top_down_10col_10row_256px', 'assets/imported/characters/tree_idle_top-down_10col_10row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 10x10
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_10col_10row_256px');
    scene.load.spritesheet('imp_tree_idle_top_down_8col_13row_256px_1', 'assets/imported/characters/tree_idle_top-down_8col_13row_256px (1).png', { frameWidth: 256, frameHeight: 256 }); // 8x13
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_8col_13row_256px_1');
    scene.load.spritesheet('imp_tree_idle_top_down_8col_13row_256px', 'assets/imported/characters/tree_idle_top-down_8col_13row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 8x13
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_8col_13row_256px');
    scene.load.spritesheet('imp_tree_idle_top_down_8col_3row_256px', 'assets/imported/characters/tree_idle_top-down_8col_3row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 8x3
    IMPORTED_KEYS.characters.push('imp_tree_idle_top_down_8col_3row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanswordattack_top_down_14col_5row_256px', 'assets/imported/characters/treetitan_treetitanswordattack_top-down_14col_5row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 14x5
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanswordattack_top_down_14col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanswordattack_top_down_6col_5row_256px', 'assets/imported/characters/treetitan_treetitanswordattack_top-down_6col_5row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 6x5
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanswordattack_top_down_6col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanswordattack_top_down_7col_5row_256px', 'assets/imported/characters/treetitan_treetitanswordattack_top-down_7col_5row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 7x5
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanswordattack_top_down_7col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanwalk_top_down_10col_5row_256px', 'assets/imported/characters/treetitan_treetitanwalk_top-down_10col_5row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 10x5
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanwalk_top_down_10col_5row_256px');
    scene.load.spritesheet('imp_treetitan_treetitanwalk_top_down_6col_10row_256px', 'assets/imported/characters/treetitan_treetitanwalk_top-down_6col_10row_256px.png', { frameWidth: 256, frameHeight: 256 }); // 6x10
    IMPORTED_KEYS.characters.push('imp_treetitan_treetitanwalk_top_down_6col_10row_256px');

    // ---- VFX (single-frame icons) ----
    scene.load.image('imp_vfx_cure1', 'assets/imported/vfx/Cure1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure1');
    scene.load.image('imp_vfx_cure2', 'assets/imported/vfx/Cure2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure2');
    scene.load.image('imp_vfx_cure3', 'assets/imported/vfx/Cure3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure3');
    scene.load.image('imp_vfx_cure4', 'assets/imported/vfx/Cure4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_cure4');
    scene.load.image('imp_vfx_curse', 'assets/imported/vfx/Curse.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_curse');
    scene.load.image('imp_vfx_darkness1', 'assets/imported/vfx/Darkness1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness1');
    scene.load.image('imp_vfx_darkness3', 'assets/imported/vfx/Darkness3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness3');
    scene.load.image('imp_vfx_darkness4', 'assets/imported/vfx/Darkness4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness4');
    scene.load.image('imp_vfx_darkness5', 'assets/imported/vfx/Darkness5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_darkness5');
    scene.load.image('imp_vfx_earth1', 'assets/imported/vfx/Earth1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth1');
    scene.load.image('imp_vfx_earth2', 'assets/imported/vfx/Earth2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth2');
    scene.load.image('imp_vfx_earth3', 'assets/imported/vfx/Earth3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth3');
    scene.load.image('imp_vfx_earth5', 'assets/imported/vfx/Earth5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_earth5');
    scene.load.image('imp_vfx_explosion1', 'assets/imported/vfx/Explosion1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_explosion1');
    scene.load.image('imp_vfx_explosion2', 'assets/imported/vfx/Explosion2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_explosion2');
    scene.load.image('imp_vfx_fire1', 'assets/imported/vfx/Fire1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_fire1');
    scene.load.image('imp_vfx_fire2', 'assets/imported/vfx/Fire2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_fire2');
    scene.load.image('imp_vfx_fire3', 'assets/imported/vfx/Fire3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_fire3');
    scene.load.image('imp_vfx_gun1', 'assets/imported/vfx/Gun1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_gun1');
    scene.load.image('imp_vfx_gun2', 'assets/imported/vfx/Gun2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_gun2');
    scene.load.image('imp_vfx_gun3', 'assets/imported/vfx/Gun3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_gun3');
    scene.load.image('imp_vfx_hit2', 'assets/imported/vfx/Hit2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hit2');
    scene.load.image('imp_vfx_hitfire', 'assets/imported/vfx/HitFire.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitfire');
    scene.load.image('imp_vfx_hitice', 'assets/imported/vfx/HitIce.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitice');
    scene.load.image('imp_vfx_hitphoton', 'assets/imported/vfx/HitPhoton.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitphoton');
    scene.load.image('imp_vfx_hitspecial1', 'assets/imported/vfx/HitSpecial1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitspecial1');
    scene.load.image('imp_vfx_hitspecial2', 'assets/imported/vfx/HitSpecial2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_hitspecial2');
    scene.load.image('imp_vfx_holy1', 'assets/imported/vfx/Holy1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy1');
    scene.load.image('imp_vfx_holy2', 'assets/imported/vfx/Holy2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy2');
    scene.load.image('imp_vfx_holy3', 'assets/imported/vfx/Holy3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy3');
    scene.load.image('imp_vfx_holy4', 'assets/imported/vfx/Holy4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy4');
    scene.load.image('imp_vfx_holy5', 'assets/imported/vfx/Holy5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_holy5');
    scene.load.image('imp_vfx_howl', 'assets/imported/vfx/Howl.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_howl');
    scene.load.image('imp_vfx_ice2', 'assets/imported/vfx/Ice2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice2');
    scene.load.image('imp_vfx_ice3', 'assets/imported/vfx/Ice3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice3');
    scene.load.image('imp_vfx_ice4', 'assets/imported/vfx/Ice4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice4');
    scene.load.image('imp_vfx_ice5', 'assets/imported/vfx/Ice5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_ice5');
    scene.load.image('imp_vfx_laser1', 'assets/imported/vfx/Laser1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_laser1');
    scene.load.image('imp_vfx_light_balls_tree1', 'assets/imported/vfx/Light_balls_tree1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_light_balls_tree1');
    scene.load.image('imp_vfx_light_balls_tree2', 'assets/imported/vfx/Light_balls_tree2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_light_balls_tree2');
    scene.load.image('imp_vfx_light_balls_tree3', 'assets/imported/vfx/Light_balls_tree3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_light_balls_tree3');
    scene.load.image('imp_vfx_slashspecial1', 'assets/imported/vfx/SlashSpecial1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashspecial1');
    scene.load.image('imp_vfx_slashspecial2', 'assets/imported/vfx/SlashSpecial2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashspecial2');
    scene.load.image('imp_vfx_slashspecial3', 'assets/imported/vfx/SlashSpecial3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashspecial3');
    scene.load.image('imp_vfx_slashthunder', 'assets/imported/vfx/SlashThunder.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_slashthunder');
    scene.load.image('imp_vfx_song', 'assets/imported/vfx/Song.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_song');
    scene.load.image('imp_vfx_sonic', 'assets/imported/vfx/Sonic.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_sonic');
    scene.load.image('imp_vfx_special1', 'assets/imported/vfx/Special1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_special1');
    scene.load.image('imp_vfx_special2', 'assets/imported/vfx/Special2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_special2');
    scene.load.image('imp_vfx_special3', 'assets/imported/vfx/Special3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_special3');
    scene.load.image('imp_vfx_statechaos', 'assets/imported/vfx/StateChaos.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statechaos');
    scene.load.image('imp_vfx_statedark', 'assets/imported/vfx/StateDark.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedark');
    scene.load.image('imp_vfx_statedeath', 'assets/imported/vfx/StateDeath.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedeath');
    scene.load.image('imp_vfx_statedown1', 'assets/imported/vfx/StateDown1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedown1');
    scene.load.image('imp_vfx_statedown2', 'assets/imported/vfx/StateDown2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedown2');
    scene.load.image('imp_vfx_statedown3', 'assets/imported/vfx/StateDown3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statedown3');
    scene.load.image('imp_vfx_stateparalys', 'assets/imported/vfx/StateParalys.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stateparalys');
    scene.load.image('imp_vfx_statepoison', 'assets/imported/vfx/StatePoison.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statepoison');
    scene.load.image('imp_vfx_statesilent', 'assets/imported/vfx/StateSilent.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statesilent');
    scene.load.image('imp_vfx_statesleep', 'assets/imported/vfx/StateSleep.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_statesleep');
    scene.load.image('imp_vfx_stateup1', 'assets/imported/vfx/StateUp1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stateup1');
    scene.load.image('imp_vfx_stateup2', 'assets/imported/vfx/StateUp2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stateup2');
    scene.load.image('imp_vfx_stick', 'assets/imported/vfx/Stick.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stick');
    scene.load.image('imp_vfx_stickphoton', 'assets/imported/vfx/StickPhoton.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickphoton');
    scene.load.image('imp_vfx_stickspecial1', 'assets/imported/vfx/StickSpecial1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickspecial1');
    scene.load.image('imp_vfx_stickspecial2', 'assets/imported/vfx/StickSpecial2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickspecial2');
    scene.load.image('imp_vfx_stickspecial3', 'assets/imported/vfx/StickSpecial3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_stickspecial3');
    scene.load.image('imp_vfx_thunder1', 'assets/imported/vfx/Thunder1.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder1');
    scene.load.image('imp_vfx_thunder2', 'assets/imported/vfx/Thunder2.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder2');
    scene.load.image('imp_vfx_thunder3', 'assets/imported/vfx/Thunder3.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder3');
    scene.load.image('imp_vfx_thunder4', 'assets/imported/vfx/Thunder4.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder4');
    scene.load.image('imp_vfx_thunder5', 'assets/imported/vfx/Thunder5.png');
    IMPORTED_KEYS.vfx.push('imp_vfx_thunder5');

    // ---- Environment props ----
    scene.load.image('imp_env_1101', 'assets/imported/environment/1101.png');
    IMPORTED_KEYS.environment.push('imp_env_1101');
    scene.load.image('imp_env_1102', 'assets/imported/environment/1102.png');
    IMPORTED_KEYS.environment.push('imp_env_1102');
    scene.load.image('imp_env_1103', 'assets/imported/environment/1103.png');
    IMPORTED_KEYS.environment.push('imp_env_1103');
    scene.load.image('imp_env_1104', 'assets/imported/environment/1104.png');
    IMPORTED_KEYS.environment.push('imp_env_1104');
    scene.load.image('imp_env_1111', 'assets/imported/environment/1111.png');
    IMPORTED_KEYS.environment.push('imp_env_1111');
    scene.load.image('imp_env_1112', 'assets/imported/environment/1112.png');
    IMPORTED_KEYS.environment.push('imp_env_1112');
    scene.load.image('imp_env_1113', 'assets/imported/environment/1113.png');
    IMPORTED_KEYS.environment.push('imp_env_1113');
    scene.load.image('imp_env_1114', 'assets/imported/environment/1114.png');
    IMPORTED_KEYS.environment.push('imp_env_1114');
    scene.load.image('imp_env_1121', 'assets/imported/environment/1121.png');
    IMPORTED_KEYS.environment.push('imp_env_1121');
    scene.load.image('imp_env_1122', 'assets/imported/environment/1122.png');
    IMPORTED_KEYS.environment.push('imp_env_1122');
    scene.load.image('imp_env_1123', 'assets/imported/environment/1123.png');
    IMPORTED_KEYS.environment.push('imp_env_1123');
    scene.load.image('imp_env_1124', 'assets/imported/environment/1124.png');
    IMPORTED_KEYS.environment.push('imp_env_1124');
    scene.load.image('imp_env_20260215145217_9e5a3639', 'assets/imported/environment/20260215145217_9e5a3639.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215145217_9e5a3639');
    scene.load.image('imp_env_20260215145239_0fcfa687', 'assets/imported/environment/20260215145239_0fcfa687.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215145239_0fcfa687');
    scene.load.image('imp_env_20260215145541_65f94c8b', 'assets/imported/environment/20260215145541_65f94c8b.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215145541_65f94c8b');
    scene.load.image('imp_env_20260215145900_6fb11998', 'assets/imported/environment/20260215145900_6fb11998.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215145900_6fb11998');
    scene.load.image('imp_env_20260215150018_8d153ff7', 'assets/imported/environment/20260215150018_8d153ff7.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150018_8d153ff7');
    scene.load.image('imp_env_20260215150202_40b4ea4d', 'assets/imported/environment/20260215150202_40b4ea4d.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150202_40b4ea4d');
    scene.load.image('imp_env_20260215150419_0a3af626', 'assets/imported/environment/20260215150419_0a3af626.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150419_0a3af626');
    scene.load.image('imp_env_20260215150455_50986361', 'assets/imported/environment/20260215150455_50986361.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150455_50986361');
    scene.load.image('imp_env_20260215150630_9c47c086', 'assets/imported/environment/20260215150630_9c47c086.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150630_9c47c086');
    scene.load.image('imp_env_20260215150654_089232aa', 'assets/imported/environment/20260215150654_089232aa.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150654_089232aa');
    scene.load.image('imp_env_20260215150721_0ee57ad8', 'assets/imported/environment/20260215150721_0ee57ad8.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150721_0ee57ad8');
    scene.load.image('imp_env_20260215150836_066ec670', 'assets/imported/environment/20260215150836_066ec670.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150836_066ec670');
    scene.load.image('imp_env_20260215150927_71c35160', 'assets/imported/environment/20260215150927_71c35160.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150927_71c35160');
    scene.load.image('imp_env_20260215150933_c98423b1', 'assets/imported/environment/20260215150933_c98423b1.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215150933_c98423b1');
    scene.load.image('imp_env_20260215151122_c4921aae', 'assets/imported/environment/20260215151122_c4921aae.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215151122_c4921aae');
    scene.load.image('imp_env_20260215151149_67fad25f', 'assets/imported/environment/20260215151149_67fad25f.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215151149_67fad25f');
    scene.load.image('imp_env_20260215151403_042765d2', 'assets/imported/environment/20260215151403_042765d2.png');
    IMPORTED_KEYS.environment.push('imp_env_20260215151403_042765d2');
    scene.load.image('imp_env_20260215151522_8002731f_1', 'assets/imported/environment/20260215151522_8002731f (1).png');
    IMPORTED_KEYS.environment.push('imp_env_20260215151522_8002731f_1');
    scene.load.image('imp_env_766', 'assets/imported/environment/766.png');
    IMPORTED_KEYS.environment.push('imp_env_766');
    scene.load.image('imp_env_767', 'assets/imported/environment/767.png');
    IMPORTED_KEYS.environment.push('imp_env_767');
    scene.load.image('imp_env_768', 'assets/imported/environment/768.png');
    IMPORTED_KEYS.environment.push('imp_env_768');
    scene.load.image('imp_env_769', 'assets/imported/environment/769.png');
    IMPORTED_KEYS.environment.push('imp_env_769');
    scene.load.image('imp_env_776', 'assets/imported/environment/776.png');
    IMPORTED_KEYS.environment.push('imp_env_776');
    scene.load.image('imp_env_777', 'assets/imported/environment/777.png');
    IMPORTED_KEYS.environment.push('imp_env_777');
    scene.load.image('imp_env_778', 'assets/imported/environment/778.png');
    IMPORTED_KEYS.environment.push('imp_env_778');
    scene.load.image('imp_env_779', 'assets/imported/environment/779.png');
    IMPORTED_KEYS.environment.push('imp_env_779');
    scene.load.image('imp_env_786', 'assets/imported/environment/786.png');
    IMPORTED_KEYS.environment.push('imp_env_786');
    scene.load.image('imp_env_787', 'assets/imported/environment/787.png');
    IMPORTED_KEYS.environment.push('imp_env_787');
    scene.load.image('imp_env_788', 'assets/imported/environment/788.png');
    IMPORTED_KEYS.environment.push('imp_env_788');
    scene.load.image('imp_env_789', 'assets/imported/environment/789.png');
    IMPORTED_KEYS.environment.push('imp_env_789');
    scene.load.image('imp_env_825', 'assets/imported/environment/825.png');
    IMPORTED_KEYS.environment.push('imp_env_825');
    scene.load.image('imp_env_826', 'assets/imported/environment/826.png');
    IMPORTED_KEYS.environment.push('imp_env_826');
    scene.load.image('imp_env_827', 'assets/imported/environment/827.png');
    IMPORTED_KEYS.environment.push('imp_env_827');
    scene.load.image('imp_env_828', 'assets/imported/environment/828.png');
    IMPORTED_KEYS.environment.push('imp_env_828');
    scene.load.image('imp_env_835', 'assets/imported/environment/835.png');
    IMPORTED_KEYS.environment.push('imp_env_835');
    scene.load.image('imp_env_836', 'assets/imported/environment/836.png');
    IMPORTED_KEYS.environment.push('imp_env_836');
    scene.load.image('imp_env_837', 'assets/imported/environment/837.png');
    IMPORTED_KEYS.environment.push('imp_env_837');
    scene.load.image('imp_env_838', 'assets/imported/environment/838.png');
    IMPORTED_KEYS.environment.push('imp_env_838');
    scene.load.image('imp_env_845', 'assets/imported/environment/845.png');
    IMPORTED_KEYS.environment.push('imp_env_845');
    scene.load.image('imp_env_846', 'assets/imported/environment/846.png');
    IMPORTED_KEYS.environment.push('imp_env_846');
    scene.load.image('imp_env_847', 'assets/imported/environment/847.png');
    IMPORTED_KEYS.environment.push('imp_env_847');
    scene.load.image('imp_env_848', 'assets/imported/environment/848.png');
    IMPORTED_KEYS.environment.push('imp_env_848');
    scene.load.image('imp_env_925', 'assets/imported/environment/925.png');
    IMPORTED_KEYS.environment.push('imp_env_925');
    scene.load.image('imp_env_926', 'assets/imported/environment/926.png');
    IMPORTED_KEYS.environment.push('imp_env_926');
    scene.load.image('imp_env_927', 'assets/imported/environment/927.png');
    IMPORTED_KEYS.environment.push('imp_env_927');
    scene.load.image('imp_env_928', 'assets/imported/environment/928.png');
    IMPORTED_KEYS.environment.push('imp_env_928');
    scene.load.image('imp_env_935', 'assets/imported/environment/935.png');
    IMPORTED_KEYS.environment.push('imp_env_935');
    scene.load.image('imp_env_936', 'assets/imported/environment/936.png');
    IMPORTED_KEYS.environment.push('imp_env_936');
    scene.load.image('imp_env_937', 'assets/imported/environment/937.png');
    IMPORTED_KEYS.environment.push('imp_env_937');
    scene.load.image('imp_env_938', 'assets/imported/environment/938.png');
    IMPORTED_KEYS.environment.push('imp_env_938');
    scene.load.image('imp_env_945', 'assets/imported/environment/945.png');
    IMPORTED_KEYS.environment.push('imp_env_945');
    scene.load.image('imp_env_946', 'assets/imported/environment/946.png');
    IMPORTED_KEYS.environment.push('imp_env_946');
    scene.load.image('imp_env_947', 'assets/imported/environment/947.png');
    IMPORTED_KEYS.environment.push('imp_env_947');
    scene.load.image('imp_env_948', 'assets/imported/environment/948.png');
    IMPORTED_KEYS.environment.push('imp_env_948');
    scene.load.image('imp_env_anchor_shadow1', 'assets/imported/environment/Anchor_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_anchor_shadow1');
    scene.load.image('imp_env_anchor_shadow2', 'assets/imported/environment/Anchor_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_anchor_shadow2');
    scene.load.image('imp_env_anchor_shadow3', 'assets/imported/environment/Anchor_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_anchor_shadow3');
    scene.load.image('imp_env_assets_shadows_source', 'assets/imported/environment/Assets_shadows_source.png');
    IMPORTED_KEYS.environment.push('imp_env_assets_shadows_source');
    scene.load.image('imp_env_autumn_bush1', 'assets/imported/environment/Autumn_bush1.png');
    IMPORTED_KEYS.environment.push('imp_env_autumn_bush1');
    scene.load.image('imp_env_autumn_bush2', 'assets/imported/environment/Autumn_bush2.png');
    IMPORTED_KEYS.environment.push('imp_env_autumn_bush2');
    scene.load.image('imp_env_autumn_bush3', 'assets/imported/environment/Autumn_bush3.png');
    IMPORTED_KEYS.environment.push('imp_env_autumn_bush3');
    scene.load.image('imp_env_beige_violet_coral1_shadow1', 'assets/imported/environment/Beige-violet_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral1_shadow1');
    scene.load.image('imp_env_beige_violet_coral1_shadow2', 'assets/imported/environment/Beige-violet_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral1_shadow2');
    scene.load.image('imp_env_beige_violet_coral1_shadow3', 'assets/imported/environment/Beige-violet_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral1_shadow3');
    scene.load.image('imp_env_beige_violet_coral2_shadow1', 'assets/imported/environment/Beige-violet_coral2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral2_shadow1');
    scene.load.image('imp_env_beige_violet_coral2_shadow2', 'assets/imported/environment/Beige-violet_coral2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral2_shadow2');
    scene.load.image('imp_env_beige_violet_coral2_shadow3', 'assets/imported/environment/Beige-violet_coral2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_violet_coral2_shadow3');
    scene.load.image('imp_env_beige_green_mushroom1', 'assets/imported/environment/Beige_green_mushroom1.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_green_mushroom1');
    scene.load.image('imp_env_beige_green_mushroom2', 'assets/imported/environment/Beige_green_mushroom2.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_green_mushroom2');
    scene.load.image('imp_env_beige_green_mushroom3', 'assets/imported/environment/Beige_green_mushroom3.png');
    IMPORTED_KEYS.environment.push('imp_env_beige_green_mushroom3');
    scene.load.image('imp_env_blue_beige_coral1_shadow1', 'assets/imported/environment/Blue-beige_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_beige_coral1_shadow1');
    scene.load.image('imp_env_blue_beige_coral1_shadow2', 'assets/imported/environment/Blue-beige_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_beige_coral1_shadow2');
    scene.load.image('imp_env_blue_beige_coral1_shadow3', 'assets/imported/environment/Blue-beige_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_beige_coral1_shadow3');
    scene.load.image('imp_env_blue_gray_ruins1_2', 'assets/imported/environment/Blue-gray_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins1_2');
    scene.load.image('imp_env_blue_gray_ruins1', 'assets/imported/environment/Blue-gray_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins1');
    scene.load.image('imp_env_blue_gray_ruins2_2', 'assets/imported/environment/Blue-gray_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins2_2');
    scene.load.image('imp_env_blue_gray_ruins2', 'assets/imported/environment/Blue-gray_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins2');
    scene.load.image('imp_env_blue_gray_ruins3_2', 'assets/imported/environment/Blue-gray_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins3_2');
    scene.load.image('imp_env_blue_gray_ruins3', 'assets/imported/environment/Blue-gray_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins3');
    scene.load.image('imp_env_blue_gray_ruins4_2', 'assets/imported/environment/Blue-gray_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins4_2');
    scene.load.image('imp_env_blue_gray_ruins4', 'assets/imported/environment/Blue-gray_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins4');
    scene.load.image('imp_env_blue_gray_ruins5_2', 'assets/imported/environment/Blue-gray_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins5_2');
    scene.load.image('imp_env_blue_gray_ruins5', 'assets/imported/environment/Blue-gray_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_gray_ruins5');
    scene.load.image('imp_env_blue_green_balls_tree1', 'assets/imported/environment/Blue-green_balls_tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_green_balls_tree1');
    scene.load.image('imp_env_blue_green_balls_tree2', 'assets/imported/environment/Blue-green_balls_tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_green_balls_tree2');
    scene.load.image('imp_env_blue_green_balls_tree3', 'assets/imported/environment/Blue-green_balls_tree3.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_green_balls_tree3');
    scene.load.image('imp_env_blue_coral1_shadow1', 'assets/imported/environment/Blue_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_coral1_shadow1');
    scene.load.image('imp_env_blue_coral1_shadow2', 'assets/imported/environment/Blue_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_coral1_shadow2');
    scene.load.image('imp_env_blue_coral1_shadow3', 'assets/imported/environment/Blue_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_blue_coral1_shadow3');
    scene.load.image('imp_env_broken_tree1', 'assets/imported/environment/Broken_tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_broken_tree1');
    scene.load.image('imp_env_broken_tree2', 'assets/imported/environment/Broken_tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_broken_tree2');
    scene.load.image('imp_env_brown_gray_ruins1_2', 'assets/imported/environment/Brown-gray_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins1_2');
    scene.load.image('imp_env_brown_gray_ruins1', 'assets/imported/environment/Brown-gray_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins1');
    scene.load.image('imp_env_brown_gray_ruins2_2', 'assets/imported/environment/Brown-gray_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins2_2');
    scene.load.image('imp_env_brown_gray_ruins2', 'assets/imported/environment/Brown-gray_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins2');
    scene.load.image('imp_env_brown_gray_ruins3_2', 'assets/imported/environment/Brown-gray_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins3_2');
    scene.load.image('imp_env_brown_gray_ruins3', 'assets/imported/environment/Brown-gray_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins3');
    scene.load.image('imp_env_brown_gray_ruins4_2', 'assets/imported/environment/Brown-gray_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins4_2');
    scene.load.image('imp_env_brown_gray_ruins4', 'assets/imported/environment/Brown-gray_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins4');
    scene.load.image('imp_env_brown_gray_ruins5_2', 'assets/imported/environment/Brown-gray_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins5_2');
    scene.load.image('imp_env_brown_gray_ruins5', 'assets/imported/environment/Brown-gray_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_gray_ruins5');
    scene.load.image('imp_env_brown_white_shell1_shadow1', 'assets/imported/environment/Brown-white_shell1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell1_shadow1');
    scene.load.image('imp_env_brown_white_shell1_shadow2', 'assets/imported/environment/Brown-white_shell1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell1_shadow2');
    scene.load.image('imp_env_brown_white_shell1_shadow3', 'assets/imported/environment/Brown-white_shell1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell1_shadow3');
    scene.load.image('imp_env_brown_white_shell2_shadow1', 'assets/imported/environment/Brown-white_shell2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell2_shadow1');
    scene.load.image('imp_env_brown_white_shell2_shadow2', 'assets/imported/environment/Brown-white_shell2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell2_shadow2');
    scene.load.image('imp_env_brown_white_shell2_shadow3', 'assets/imported/environment/Brown-white_shell2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_white_shell2_shadow3');
    scene.load.image('imp_env_brown_ruins1_2', 'assets/imported/environment/Brown_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins1_2');
    scene.load.image('imp_env_brown_ruins1', 'assets/imported/environment/Brown_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins1');
    scene.load.image('imp_env_brown_ruins2_2', 'assets/imported/environment/Brown_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins2_2');
    scene.load.image('imp_env_brown_ruins2', 'assets/imported/environment/Brown_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins2');
    scene.load.image('imp_env_brown_ruins3_2', 'assets/imported/environment/Brown_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins3_2');
    scene.load.image('imp_env_brown_ruins3', 'assets/imported/environment/Brown_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins3');
    scene.load.image('imp_env_brown_ruins4_2', 'assets/imported/environment/Brown_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins4_2');
    scene.load.image('imp_env_brown_ruins4', 'assets/imported/environment/Brown_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins4');
    scene.load.image('imp_env_brown_ruins5_2', 'assets/imported/environment/Brown_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins5_2');
    scene.load.image('imp_env_brown_ruins5', 'assets/imported/environment/Brown_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_brown_ruins5');
    scene.load.image('imp_env_burned_tree1', 'assets/imported/environment/Burned_tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_burned_tree1');
    scene.load.image('imp_env_burned_tree2', 'assets/imported/environment/Burned_tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_burned_tree2');
    scene.load.image('imp_env_bush_blue_flowers1', 'assets/imported/environment/Bush_blue_flowers1.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_blue_flowers1');
    scene.load.image('imp_env_bush_blue_flowers2', 'assets/imported/environment/Bush_blue_flowers2.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_blue_flowers2');
    scene.load.image('imp_env_bush_blue_flowers3', 'assets/imported/environment/Bush_blue_flowers3.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_blue_flowers3');
    scene.load.image('imp_env_bush_orange_flowers1', 'assets/imported/environment/Bush_orange_flowers1.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_orange_flowers1');
    scene.load.image('imp_env_bush_orange_flowers2', 'assets/imported/environment/Bush_orange_flowers2.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_orange_flowers2');
    scene.load.image('imp_env_bush_orange_flowers3', 'assets/imported/environment/Bush_orange_flowers3.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_orange_flowers3');
    scene.load.image('imp_env_bush_pink_flowers1', 'assets/imported/environment/Bush_pink_flowers1.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_pink_flowers1');
    scene.load.image('imp_env_bush_pink_flowers2', 'assets/imported/environment/Bush_pink_flowers2.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_pink_flowers2');
    scene.load.image('imp_env_bush_pink_flowers3', 'assets/imported/environment/Bush_pink_flowers3.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_pink_flowers3');
    scene.load.image('imp_env_bush_red_flowers1', 'assets/imported/environment/Bush_red_flowers1.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_red_flowers1');
    scene.load.image('imp_env_bush_red_flowers2', 'assets/imported/environment/Bush_red_flowers2.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_red_flowers2');
    scene.load.image('imp_env_bush_red_flowers3', 'assets/imported/environment/Bush_red_flowers3.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_red_flowers3');
    scene.load.image('imp_env_bush_simple1_1', 'assets/imported/environment/Bush_simple1_1.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_simple1_1');
    scene.load.image('imp_env_bush_simple1_2', 'assets/imported/environment/Bush_simple1_2.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_simple1_2');
    scene.load.image('imp_env_bush_simple1_3', 'assets/imported/environment/Bush_simple1_3.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_simple1_3');
    scene.load.image('imp_env_bush_simple2_1', 'assets/imported/environment/Bush_simple2_1.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_simple2_1');
    scene.load.image('imp_env_bush_simple2_2', 'assets/imported/environment/Bush_simple2_2.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_simple2_2');
    scene.load.image('imp_env_bush_simple2_3', 'assets/imported/environment/Bush_simple2_3.png');
    IMPORTED_KEYS.environment.push('imp_env_bush_simple2_3');
    scene.load.image('imp_env_cactus1_1', 'assets/imported/environment/Cactus1_1.png');
    IMPORTED_KEYS.environment.push('imp_env_cactus1_1');
    scene.load.image('imp_env_cactus1_2', 'assets/imported/environment/Cactus1_2.png');
    IMPORTED_KEYS.environment.push('imp_env_cactus1_2');
    scene.load.image('imp_env_cactus1_3', 'assets/imported/environment/Cactus1_3.png');
    IMPORTED_KEYS.environment.push('imp_env_cactus1_3');
    scene.load.image('imp_env_cactus2_1', 'assets/imported/environment/Cactus2_1.png');
    IMPORTED_KEYS.environment.push('imp_env_cactus2_1');
    scene.load.image('imp_env_cactus2_2', 'assets/imported/environment/Cactus2_2.png');
    IMPORTED_KEYS.environment.push('imp_env_cactus2_2');
    scene.load.image('imp_env_cactus2_3', 'assets/imported/environment/Cactus2_3.png');
    IMPORTED_KEYS.environment.push('imp_env_cactus2_3');
    scene.load.image('imp_env_chanterelles1', 'assets/imported/environment/Chanterelles1.png');
    IMPORTED_KEYS.environment.push('imp_env_chanterelles1');
    scene.load.image('imp_env_chanterelles2', 'assets/imported/environment/Chanterelles2.png');
    IMPORTED_KEYS.environment.push('imp_env_chanterelles2');
    scene.load.image('imp_env_chanterelles3', 'assets/imported/environment/Chanterelles3.png');
    IMPORTED_KEYS.environment.push('imp_env_chanterelles3');
    scene.load.image('imp_env_crab_shadow1', 'assets/imported/environment/Crab_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_crab_shadow1');
    scene.load.image('imp_env_crab_shadow2', 'assets/imported/environment/Crab_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_crab_shadow2');
    scene.load.image('imp_env_crab_shadow3', 'assets/imported/environment/Crab_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_crab_shadow3');
    scene.load.image('imp_env_curved_tree1', 'assets/imported/environment/Curved_tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_curved_tree1');
    scene.load.image('imp_env_curved_tree2', 'assets/imported/environment/Curved_tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_curved_tree2');
    scene.load.image('imp_env_curved_tree3', 'assets/imported/environment/Curved_tree3.png');
    IMPORTED_KEYS.environment.push('imp_env_curved_tree3');
    scene.load.image('imp_env_details_2', 'assets/imported/environment/Details (2).png');
    IMPORTED_KEYS.environment.push('imp_env_details_2');
    scene.load.image('imp_env_dragon_bones_shadow1', 'assets/imported/environment/Dragon_bones_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_dragon_bones_shadow1');
    scene.load.image('imp_env_dragon_bones_shadow2', 'assets/imported/environment/Dragon_bones_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_dragon_bones_shadow2');
    scene.load.image('imp_env_dragon_bones_shadow3', 'assets/imported/environment/Dragon_bones_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_dragon_bones_shadow3');
    scene.load.image('imp_env_ent_man', 'assets/imported/environment/Ent_man.png');
    IMPORTED_KEYS.environment.push('imp_env_ent_man');
    scene.load.image('imp_env_ent_woman', 'assets/imported/environment/Ent_woman.png');
    IMPORTED_KEYS.environment.push('imp_env_ent_woman');
    scene.load.image('imp_env_fern1_1', 'assets/imported/environment/Fern1_1.png');
    IMPORTED_KEYS.environment.push('imp_env_fern1_1');
    scene.load.image('imp_env_fern1_2', 'assets/imported/environment/Fern1_2.png');
    IMPORTED_KEYS.environment.push('imp_env_fern1_2');
    scene.load.image('imp_env_fern1_3', 'assets/imported/environment/Fern1_3.png');
    IMPORTED_KEYS.environment.push('imp_env_fern1_3');
    scene.load.image('imp_env_fern2_1', 'assets/imported/environment/Fern2_1.png');
    IMPORTED_KEYS.environment.push('imp_env_fern2_1');
    scene.load.image('imp_env_fern2_2', 'assets/imported/environment/Fern2_2.png');
    IMPORTED_KEYS.environment.push('imp_env_fern2_2');
    scene.load.image('imp_env_fern2_3', 'assets/imported/environment/Fern2_3.png');
    IMPORTED_KEYS.environment.push('imp_env_fern2_3');
    scene.load.image('imp_env_font', 'assets/imported/environment/Font.png');
    IMPORTED_KEYS.environment.push('imp_env_font');
    scene.load.image('imp_env_gray_red_coral1_shadow1', 'assets/imported/environment/Gray-red_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral1_shadow1');
    scene.load.image('imp_env_gray_red_coral1_shadow2', 'assets/imported/environment/Gray-red_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral1_shadow2');
    scene.load.image('imp_env_gray_red_coral1_shadow3', 'assets/imported/environment/Gray-red_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral1_shadow3');
    scene.load.image('imp_env_gray_red_coral2_shadow1', 'assets/imported/environment/Gray-red_coral2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral2_shadow1');
    scene.load.image('imp_env_gray_red_coral2_shadow2', 'assets/imported/environment/Gray-red_coral2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral2_shadow2');
    scene.load.image('imp_env_gray_red_coral2_shadow3', 'assets/imported/environment/Gray-red_coral2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_gray_red_coral2_shadow3');
    scene.load.image('imp_env_ground_2', 'assets/imported/environment/Ground (2).png');
    IMPORTED_KEYS.environment.push('imp_env_ground_2');
    scene.load.image('imp_env_ground', 'assets/imported/environment/Ground.png');
    IMPORTED_KEYS.environment.push('imp_env_ground');
    scene.load.image('imp_env_ground_rocks', 'assets/imported/environment/Ground_rocks.png');
    IMPORTED_KEYS.environment.push('imp_env_ground_rocks');
    scene.load.image('imp_env_living_gazebo1', 'assets/imported/environment/Living gazebo1.png');
    IMPORTED_KEYS.environment.push('imp_env_living_gazebo1');
    scene.load.image('imp_env_living_gazebo2', 'assets/imported/environment/Living gazebo2.png');
    IMPORTED_KEYS.environment.push('imp_env_living_gazebo2');
    scene.load.image('imp_env_luminous_tree1', 'assets/imported/environment/Luminous_tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_luminous_tree1');
    scene.load.image('imp_env_luminous_tree2', 'assets/imported/environment/Luminous_tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_luminous_tree2');
    scene.load.image('imp_env_luminous_tree3', 'assets/imported/environment/Luminous_tree3.png');
    IMPORTED_KEYS.environment.push('imp_env_luminous_tree3');
    scene.load.image('imp_env_luminous_tree4', 'assets/imported/environment/Luminous_tree4.png');
    IMPORTED_KEYS.environment.push('imp_env_luminous_tree4');
    scene.load.image('imp_env_mega_tree1', 'assets/imported/environment/Mega_tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_mega_tree1');
    scene.load.image('imp_env_mega_tree2', 'assets/imported/environment/Mega_tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_mega_tree2');
    scene.load.image('imp_env_mermaid_house_shadow1', 'assets/imported/environment/Mermaid_house_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_mermaid_house_shadow1');
    scene.load.image('imp_env_mermaid_house_shadow2', 'assets/imported/environment/Mermaid_house_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_mermaid_house_shadow2');
    scene.load.image('imp_env_mermaid_house_shadow3', 'assets/imported/environment/Mermaid_house_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_mermaid_house_shadow3');
    scene.load.image('imp_env_monster_fish_bones_shadow1', 'assets/imported/environment/Monster_fish_bones_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_monster_fish_bones_shadow1');
    scene.load.image('imp_env_monster_fish_bones_shadow2', 'assets/imported/environment/Monster_fish_bones_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_monster_fish_bones_shadow2');
    scene.load.image('imp_env_monster_fish_bones_shadow3', 'assets/imported/environment/Monster_fish_bones_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_monster_fish_bones_shadow3');
    scene.load.image('imp_env_objects_2', 'assets/imported/environment/Objects (2).png');
    IMPORTED_KEYS.environment.push('imp_env_objects_2');
    scene.load.image('imp_env_objects_3', 'assets/imported/environment/Objects (3).png');
    IMPORTED_KEYS.environment.push('imp_env_objects_3');
    scene.load.image('imp_env_objects', 'assets/imported/environment/Objects.png');
    IMPORTED_KEYS.environment.push('imp_env_objects');
    scene.load.image('imp_env_pearl_sea_shell1_shadow1', 'assets/imported/environment/Pearl_sea_shell1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_pearl_sea_shell1_shadow1');
    scene.load.image('imp_env_pearl_sea_shell1_shadow2', 'assets/imported/environment/Pearl_sea_shell1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_pearl_sea_shell1_shadow2');
    scene.load.image('imp_env_pearl_sea_shell1_shadow3', 'assets/imported/environment/Pearl_sea_shell1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_pearl_sea_shell1_shadow3');
    scene.load.image('imp_env_preview_2d_rpg_desert_tileset', 'assets/imported/environment/Preview_2D_RPG_Desert_Tileset.png');
    IMPORTED_KEYS.environment.push('imp_env_preview_2d_rpg_desert_tileset');
    scene.load.image('imp_env_riff1_shadow1', 'assets/imported/environment/Riff1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff1_shadow1');
    scene.load.image('imp_env_riff1_shadow2', 'assets/imported/environment/Riff1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff1_shadow2');
    scene.load.image('imp_env_riff1_shadow3', 'assets/imported/environment/Riff1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff1_shadow3');
    scene.load.image('imp_env_riff2_shadow1', 'assets/imported/environment/Riff2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff2_shadow1');
    scene.load.image('imp_env_riff2_shadow2', 'assets/imported/environment/Riff2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff2_shadow2');
    scene.load.image('imp_env_riff2_shadow3', 'assets/imported/environment/Riff2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff2_shadow3');
    scene.load.image('imp_env_riff3_shadow1', 'assets/imported/environment/Riff3_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff3_shadow1');
    scene.load.image('imp_env_riff3_shadow2', 'assets/imported/environment/Riff3_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff3_shadow2');
    scene.load.image('imp_env_riff3_shadow3', 'assets/imported/environment/Riff3_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff3_shadow3');
    scene.load.image('imp_env_riff4_shadow1', 'assets/imported/environment/Riff4_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_riff4_shadow1');
    scene.load.image('imp_env_riff4_shadow2', 'assets/imported/environment/Riff4_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_riff4_shadow2');
    scene.load.image('imp_env_riff4_shadow3', 'assets/imported/environment/Riff4_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_riff4_shadow3');
    scene.load.image('imp_env_sand_ruins1_2', 'assets/imported/environment/Sand_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins1_2');
    scene.load.image('imp_env_sand_ruins1', 'assets/imported/environment/Sand_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins1');
    scene.load.image('imp_env_sand_ruins2_2', 'assets/imported/environment/Sand_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins2_2');
    scene.load.image('imp_env_sand_ruins2', 'assets/imported/environment/Sand_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins2');
    scene.load.image('imp_env_sand_ruins3_2', 'assets/imported/environment/Sand_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins3_2');
    scene.load.image('imp_env_sand_ruins3', 'assets/imported/environment/Sand_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins3');
    scene.load.image('imp_env_sand_ruins4_2', 'assets/imported/environment/Sand_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins4_2');
    scene.load.image('imp_env_sand_ruins4', 'assets/imported/environment/Sand_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins4');
    scene.load.image('imp_env_sand_ruins5_2', 'assets/imported/environment/Sand_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins5_2');
    scene.load.image('imp_env_sand_ruins5', 'assets/imported/environment/Sand_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_sand_ruins5');
    scene.load.image('imp_env_sea_insect_shadow1', 'assets/imported/environment/Sea_insect_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_insect_shadow1');
    scene.load.image('imp_env_sea_insect_shadow2', 'assets/imported/environment/Sea_insect_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_insect_shadow2');
    scene.load.image('imp_env_sea_insect_shadow3', 'assets/imported/environment/Sea_insect_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_insect_shadow3');
    scene.load.image('imp_env_sea_urchin1_shadow1', 'assets/imported/environment/Sea_urchin1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin1_shadow1');
    scene.load.image('imp_env_sea_urchin1_shadow2', 'assets/imported/environment/Sea_urchin1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin1_shadow2');
    scene.load.image('imp_env_sea_urchin1_shadow3', 'assets/imported/environment/Sea_urchin1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin1_shadow3');
    scene.load.image('imp_env_sea_urchin2_shadow1', 'assets/imported/environment/Sea_urchin2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin2_shadow1');
    scene.load.image('imp_env_sea_urchin2_shadow2', 'assets/imported/environment/Sea_urchin2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin2_shadow2');
    scene.load.image('imp_env_sea_urchin2_shadow3', 'assets/imported/environment/Sea_urchin2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_sea_urchin2_shadow3');
    scene.load.image('imp_env_ship1_shadow1', 'assets/imported/environment/Ship1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_ship1_shadow1');
    scene.load.image('imp_env_ship1_shadow2', 'assets/imported/environment/Ship1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_ship1_shadow2');
    scene.load.image('imp_env_ship1_shadow3', 'assets/imported/environment/Ship1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_ship1_shadow3');
    scene.load.image('imp_env_ship2_shadow1', 'assets/imported/environment/Ship2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_ship2_shadow1');
    scene.load.image('imp_env_ship2_shadow2', 'assets/imported/environment/Ship2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_ship2_shadow2');
    scene.load.image('imp_env_ship2_shadow3', 'assets/imported/environment/Ship2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_ship2_shadow3');
    scene.load.image('imp_env_snow_bush1', 'assets/imported/environment/Snow_bush1.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_bush1');
    scene.load.image('imp_env_snow_bush2', 'assets/imported/environment/Snow_bush2.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_bush2');
    scene.load.image('imp_env_snow_bush3', 'assets/imported/environment/Snow_bush3.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_bush3');
    scene.load.image('imp_env_snow_ruins1_2', 'assets/imported/environment/Snow_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins1_2');
    scene.load.image('imp_env_snow_ruins1', 'assets/imported/environment/Snow_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins1');
    scene.load.image('imp_env_snow_ruins2_2', 'assets/imported/environment/Snow_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins2_2');
    scene.load.image('imp_env_snow_ruins2', 'assets/imported/environment/Snow_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins2');
    scene.load.image('imp_env_snow_ruins3_2', 'assets/imported/environment/Snow_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins3_2');
    scene.load.image('imp_env_snow_ruins3', 'assets/imported/environment/Snow_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins3');
    scene.load.image('imp_env_snow_ruins4_2', 'assets/imported/environment/Snow_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins4_2');
    scene.load.image('imp_env_snow_ruins4', 'assets/imported/environment/Snow_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins4');
    scene.load.image('imp_env_snow_ruins5_2', 'assets/imported/environment/Snow_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins5_2');
    scene.load.image('imp_env_snow_ruins5', 'assets/imported/environment/Snow_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_snow_ruins5');
    scene.load.image('imp_env_starfish1_shadow1', 'assets/imported/environment/Starfish1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish1_shadow1');
    scene.load.image('imp_env_starfish1_shadow2', 'assets/imported/environment/Starfish1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish1_shadow2');
    scene.load.image('imp_env_starfish1_shadow3', 'assets/imported/environment/Starfish1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish1_shadow3');
    scene.load.image('imp_env_starfish2_shadow1', 'assets/imported/environment/Starfish2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish2_shadow1');
    scene.load.image('imp_env_starfish2_shadow2', 'assets/imported/environment/Starfish2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish2_shadow2');
    scene.load.image('imp_env_starfish2_shadow3', 'assets/imported/environment/Starfish2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_starfish2_shadow3');
    scene.load.image('imp_env_statue1_shadow1', 'assets/imported/environment/Statue1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_statue1_shadow1');
    scene.load.image('imp_env_statue1_shadow2', 'assets/imported/environment/Statue1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_statue1_shadow2');
    scene.load.image('imp_env_statue1_shadow3', 'assets/imported/environment/Statue1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_statue1_shadow3');
    scene.load.image('imp_env_statue2_shadow1', 'assets/imported/environment/Statue2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_statue2_shadow1');
    scene.load.image('imp_env_statue2_shadow2', 'assets/imported/environment/Statue2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_statue2_shadow2');
    scene.load.image('imp_env_statue2_shadow3', 'assets/imported/environment/Statue2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_statue2_shadow3');
    scene.load.image('imp_env_steering_wheel_shadow1', 'assets/imported/environment/Steering_wheel_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_steering_wheel_shadow1');
    scene.load.image('imp_env_steering_wheel_shadow2', 'assets/imported/environment/Steering_wheel_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_steering_wheel_shadow2');
    scene.load.image('imp_env_steering_wheel_shadow3', 'assets/imported/environment/Steering_wheel_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_steering_wheel_shadow3');
    scene.load.image('imp_env_swirling_tree1', 'assets/imported/environment/Swirling tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_swirling_tree1');
    scene.load.image('imp_env_swirling_tree2', 'assets/imported/environment/Swirling tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_swirling_tree2');
    scene.load.image('imp_env_swirling_tree3', 'assets/imported/environment/Swirling tree3.png');
    IMPORTED_KEYS.environment.push('imp_env_swirling_tree3');
    scene.load.image('imp_env_tree_idol_deer', 'assets/imported/environment/Tree_idol_deer.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_idol_deer');
    scene.load.image('imp_env_tree_idol_dragon', 'assets/imported/environment/Tree_idol_dragon.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_idol_dragon');
    scene.load.image('imp_env_tree_idol_human', 'assets/imported/environment/Tree_idol_human.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_idol_human');
    scene.load.image('imp_env_tree_idol_wolf', 'assets/imported/environment/Tree_idol_wolf.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_idol_wolf');
    scene.load.image('imp_env_turtle_shell_shadow1', 'assets/imported/environment/Turtle_shell_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_turtle_shell_shadow1');
    scene.load.image('imp_env_turtle_shell_shadow2', 'assets/imported/environment/Turtle_shell_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_turtle_shell_shadow2');
    scene.load.image('imp_env_turtle_shell_shadow3', 'assets/imported/environment/Turtle_shell_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_turtle_shell_shadow3');
    scene.load.image('imp_env_violet_pink_coral1_shadow1', 'assets/imported/environment/Violet-pink_coral1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral1_shadow1');
    scene.load.image('imp_env_violet_pink_coral1_shadow2', 'assets/imported/environment/Violet-pink_coral1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral1_shadow2');
    scene.load.image('imp_env_violet_pink_coral1_shadow3', 'assets/imported/environment/Violet-pink_coral1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral1_shadow3');
    scene.load.image('imp_env_violet_pink_coral2_shadow1', 'assets/imported/environment/Violet-pink_coral2_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral2_shadow1');
    scene.load.image('imp_env_violet_pink_coral2_shadow2', 'assets/imported/environment/Violet-pink_coral2_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral2_shadow2');
    scene.load.image('imp_env_violet_pink_coral2_shadow3', 'assets/imported/environment/Violet-pink_coral2_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral2_shadow3');
    scene.load.image('imp_env_violet_pink_coral3_shadow1', 'assets/imported/environment/Violet-pink_coral3_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral3_shadow1');
    scene.load.image('imp_env_violet_pink_coral3_shadow2', 'assets/imported/environment/Violet-pink_coral3_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral3_shadow2');
    scene.load.image('imp_env_violet_pink_coral3_shadow3', 'assets/imported/environment/Violet-pink_coral3_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_violet_pink_coral3_shadow3');
    scene.load.image('imp_env_water_ruins1_2', 'assets/imported/environment/Water_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins1_2');
    scene.load.image('imp_env_water_ruins1', 'assets/imported/environment/Water_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins1');
    scene.load.image('imp_env_water_ruins2_2', 'assets/imported/environment/Water_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins2_2');
    scene.load.image('imp_env_water_ruins2', 'assets/imported/environment/Water_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins2');
    scene.load.image('imp_env_water_ruins3_2', 'assets/imported/environment/Water_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins3_2');
    scene.load.image('imp_env_water_ruins3', 'assets/imported/environment/Water_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins3');
    scene.load.image('imp_env_water_ruins4_2', 'assets/imported/environment/Water_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins4_2');
    scene.load.image('imp_env_water_ruins4', 'assets/imported/environment/Water_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins4');
    scene.load.image('imp_env_water_ruins5_2', 'assets/imported/environment/Water_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins5_2');
    scene.load.image('imp_env_water_ruins5', 'assets/imported/environment/Water_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_water_ruins5');
    scene.load.image('imp_env_white_red_mushroom1', 'assets/imported/environment/White-red_mushroom1.png');
    IMPORTED_KEYS.environment.push('imp_env_white_red_mushroom1');
    scene.load.image('imp_env_white_red_mushroom2', 'assets/imported/environment/White-red_mushroom2.png');
    IMPORTED_KEYS.environment.push('imp_env_white_red_mushroom2');
    scene.load.image('imp_env_white_red_mushroom3', 'assets/imported/environment/White-red_mushroom3.png');
    IMPORTED_KEYS.environment.push('imp_env_white_red_mushroom3');
    scene.load.image('imp_env_white_ruins1_2', 'assets/imported/environment/White_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins1_2');
    scene.load.image('imp_env_white_ruins1', 'assets/imported/environment/White_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins1');
    scene.load.image('imp_env_white_ruins2_2', 'assets/imported/environment/White_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins2_2');
    scene.load.image('imp_env_white_ruins2', 'assets/imported/environment/White_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins2');
    scene.load.image('imp_env_white_ruins3_2', 'assets/imported/environment/White_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins3_2');
    scene.load.image('imp_env_white_ruins3', 'assets/imported/environment/White_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins3');
    scene.load.image('imp_env_white_ruins4_2', 'assets/imported/environment/White_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins4_2');
    scene.load.image('imp_env_white_ruins4', 'assets/imported/environment/White_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins4');
    scene.load.image('imp_env_white_ruins5_2', 'assets/imported/environment/White_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins5_2');
    scene.load.image('imp_env_white_ruins5', 'assets/imported/environment/White_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_white_ruins5');
    scene.load.image('imp_env_white_tree1', 'assets/imported/environment/White_tree1.png');
    IMPORTED_KEYS.environment.push('imp_env_white_tree1');
    scene.load.image('imp_env_white_tree2', 'assets/imported/environment/White_tree2.png');
    IMPORTED_KEYS.environment.push('imp_env_white_tree2');
    scene.load.image('imp_env_willow1', 'assets/imported/environment/Willow1.png');
    IMPORTED_KEYS.environment.push('imp_env_willow1');
    scene.load.image('imp_env_willow2', 'assets/imported/environment/Willow2.png');
    IMPORTED_KEYS.environment.push('imp_env_willow2');
    scene.load.image('imp_env_willow3', 'assets/imported/environment/Willow3.png');
    IMPORTED_KEYS.environment.push('imp_env_willow3');
    scene.load.image('imp_env_yellow_white_gray_shell1_shadow1', 'assets/imported/environment/Yellow-white-gray_shell1_shadow1.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_white_gray_shell1_shadow1');
    scene.load.image('imp_env_yellow_white_gray_shell1_shadow2', 'assets/imported/environment/Yellow-white-gray_shell1_shadow2.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_white_gray_shell1_shadow2');
    scene.load.image('imp_env_yellow_white_gray_shell1_shadow3', 'assets/imported/environment/Yellow-white-gray_shell1_shadow3.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_white_gray_shell1_shadow3');
    scene.load.image('imp_env_yellow_ruins1_2', 'assets/imported/environment/Yellow_ruins1 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins1_2');
    scene.load.image('imp_env_yellow_ruins1', 'assets/imported/environment/Yellow_ruins1.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins1');
    scene.load.image('imp_env_yellow_ruins2_2', 'assets/imported/environment/Yellow_ruins2 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins2_2');
    scene.load.image('imp_env_yellow_ruins2', 'assets/imported/environment/Yellow_ruins2.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins2');
    scene.load.image('imp_env_yellow_ruins3_2', 'assets/imported/environment/Yellow_ruins3 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins3_2');
    scene.load.image('imp_env_yellow_ruins3', 'assets/imported/environment/Yellow_ruins3.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins3');
    scene.load.image('imp_env_yellow_ruins4_2', 'assets/imported/environment/Yellow_ruins4 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins4_2');
    scene.load.image('imp_env_yellow_ruins4', 'assets/imported/environment/Yellow_ruins4.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins4');
    scene.load.image('imp_env_yellow_ruins5_2', 'assets/imported/environment/Yellow_ruins5 (2).png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins5_2');
    scene.load.image('imp_env_yellow_ruins5', 'assets/imported/environment/Yellow_ruins5.png');
    IMPORTED_KEYS.environment.push('imp_env_yellow_ruins5');
    scene.load.image('imp_env_bg', 'assets/imported/environment/bg.png');
    IMPORTED_KEYS.environment.push('imp_env_bg');
    scene.load.image('imp_env_bridges_2', 'assets/imported/environment/bridges (2).png');
    IMPORTED_KEYS.environment.push('imp_env_bridges_2');
    scene.load.image('imp_env_bridges', 'assets/imported/environment/bridges.png');
    IMPORTED_KEYS.environment.push('imp_env_bridges');
    scene.load.image('imp_env_building_1', 'assets/imported/environment/building_1.png');
    IMPORTED_KEYS.environment.push('imp_env_building_1');
    scene.load.image('imp_env_building_2', 'assets/imported/environment/building_2.png');
    IMPORTED_KEYS.environment.push('imp_env_building_2');
    scene.load.image('imp_env_building_3', 'assets/imported/environment/building_3.png');
    IMPORTED_KEYS.environment.push('imp_env_building_3');
    scene.load.image('imp_env_building_4', 'assets/imported/environment/building_4.png');
    IMPORTED_KEYS.environment.push('imp_env_building_4');
    scene.load.image('imp_env_building_5', 'assets/imported/environment/building_5.png');
    IMPORTED_KEYS.environment.push('imp_env_building_5');
    scene.load.image('imp_env_decor_1', 'assets/imported/environment/decor_1.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_1');
    scene.load.image('imp_env_decor_2', 'assets/imported/environment/decor_2.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_2');
    scene.load.image('imp_env_decor_3', 'assets/imported/environment/decor_3.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_3');
    scene.load.image('imp_env_decor_4', 'assets/imported/environment/decor_4.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_4');
    scene.load.image('imp_env_decor_5', 'assets/imported/environment/decor_5.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_5');
    scene.load.image('imp_env_decor_6', 'assets/imported/environment/decor_6.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_6');
    scene.load.image('imp_env_decor_7', 'assets/imported/environment/decor_7.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_7');
    scene.load.image('imp_env_decor_8', 'assets/imported/environment/decor_8.png');
    IMPORTED_KEYS.environment.push('imp_env_decor_8');
    scene.load.image('imp_env_details_3', 'assets/imported/environment/details (3).png');
    IMPORTED_KEYS.environment.push('imp_env_details_3');
    scene.load.image('imp_env_details', 'assets/imported/environment/details.png');
    IMPORTED_KEYS.environment.push('imp_env_details');
    scene.load.image('imp_env_greenery_1', 'assets/imported/environment/greenery_1.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_1');
    scene.load.image('imp_env_greenery_10', 'assets/imported/environment/greenery_10.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_10');
    scene.load.image('imp_env_greenery_2', 'assets/imported/environment/greenery_2.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_2');
    scene.load.image('imp_env_greenery_3', 'assets/imported/environment/greenery_3.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_3');
    scene.load.image('imp_env_greenery_4', 'assets/imported/environment/greenery_4.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_4');
    scene.load.image('imp_env_greenery_5', 'assets/imported/environment/greenery_5.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_5');
    scene.load.image('imp_env_greenery_6', 'assets/imported/environment/greenery_6.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_6');
    scene.load.image('imp_env_greenery_7', 'assets/imported/environment/greenery_7.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_7');
    scene.load.image('imp_env_greenery_8', 'assets/imported/environment/greenery_8.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_8');
    scene.load.image('imp_env_greenery_9', 'assets/imported/environment/greenery_9.png');
    IMPORTED_KEYS.environment.push('imp_env_greenery_9');
    scene.load.image('imp_env_lake', 'assets/imported/environment/lake.png');
    IMPORTED_KEYS.environment.push('imp_env_lake');
    scene.load.image('imp_env_land_1', 'assets/imported/environment/land_1.png');
    IMPORTED_KEYS.environment.push('imp_env_land_1');
    scene.load.image('imp_env_land_10', 'assets/imported/environment/land_10.png');
    IMPORTED_KEYS.environment.push('imp_env_land_10');
    scene.load.image('imp_env_land_11', 'assets/imported/environment/land_11.png');
    IMPORTED_KEYS.environment.push('imp_env_land_11');
    scene.load.image('imp_env_land_12', 'assets/imported/environment/land_12.png');
    IMPORTED_KEYS.environment.push('imp_env_land_12');
    scene.load.image('imp_env_land_13', 'assets/imported/environment/land_13.png');
    IMPORTED_KEYS.environment.push('imp_env_land_13');
    scene.load.image('imp_env_land_14', 'assets/imported/environment/land_14.png');
    IMPORTED_KEYS.environment.push('imp_env_land_14');
    scene.load.image('imp_env_land_15', 'assets/imported/environment/land_15.png');
    IMPORTED_KEYS.environment.push('imp_env_land_15');
    scene.load.image('imp_env_land_16', 'assets/imported/environment/land_16.png');
    IMPORTED_KEYS.environment.push('imp_env_land_16');
    scene.load.image('imp_env_land_17', 'assets/imported/environment/land_17.png');
    IMPORTED_KEYS.environment.push('imp_env_land_17');
    scene.load.image('imp_env_land_18', 'assets/imported/environment/land_18.png');
    IMPORTED_KEYS.environment.push('imp_env_land_18');
    scene.load.image('imp_env_land_2', 'assets/imported/environment/land_2.png');
    IMPORTED_KEYS.environment.push('imp_env_land_2');
    scene.load.image('imp_env_land_3', 'assets/imported/environment/land_3.png');
    IMPORTED_KEYS.environment.push('imp_env_land_3');
    scene.load.image('imp_env_land_4', 'assets/imported/environment/land_4.png');
    IMPORTED_KEYS.environment.push('imp_env_land_4');
    scene.load.image('imp_env_land_5', 'assets/imported/environment/land_5.png');
    IMPORTED_KEYS.environment.push('imp_env_land_5');
    scene.load.image('imp_env_land_6', 'assets/imported/environment/land_6.png');
    IMPORTED_KEYS.environment.push('imp_env_land_6');
    scene.load.image('imp_env_land_7', 'assets/imported/environment/land_7.png');
    IMPORTED_KEYS.environment.push('imp_env_land_7');
    scene.load.image('imp_env_land_8', 'assets/imported/environment/land_8.png');
    IMPORTED_KEYS.environment.push('imp_env_land_8');
    scene.load.image('imp_env_land_9', 'assets/imported/environment/land_9.png');
    IMPORTED_KEYS.environment.push('imp_env_land_9');
    scene.load.image('imp_env_road_1', 'assets/imported/environment/road_1.png');
    IMPORTED_KEYS.environment.push('imp_env_road_1');
    scene.load.image('imp_env_road_10', 'assets/imported/environment/road_10.png');
    IMPORTED_KEYS.environment.push('imp_env_road_10');
    scene.load.image('imp_env_road_11', 'assets/imported/environment/road_11.png');
    IMPORTED_KEYS.environment.push('imp_env_road_11');
    scene.load.image('imp_env_road_12', 'assets/imported/environment/road_12.png');
    IMPORTED_KEYS.environment.push('imp_env_road_12');
    scene.load.image('imp_env_road_13', 'assets/imported/environment/road_13.png');
    IMPORTED_KEYS.environment.push('imp_env_road_13');
    scene.load.image('imp_env_road_14', 'assets/imported/environment/road_14.png');
    IMPORTED_KEYS.environment.push('imp_env_road_14');
    scene.load.image('imp_env_road_15', 'assets/imported/environment/road_15.png');
    IMPORTED_KEYS.environment.push('imp_env_road_15');
    scene.load.image('imp_env_road_16', 'assets/imported/environment/road_16.png');
    IMPORTED_KEYS.environment.push('imp_env_road_16');
    scene.load.image('imp_env_road_17', 'assets/imported/environment/road_17.png');
    IMPORTED_KEYS.environment.push('imp_env_road_17');
    scene.load.image('imp_env_road_18', 'assets/imported/environment/road_18.png');
    IMPORTED_KEYS.environment.push('imp_env_road_18');
    scene.load.image('imp_env_road_19', 'assets/imported/environment/road_19.png');
    IMPORTED_KEYS.environment.push('imp_env_road_19');
    scene.load.image('imp_env_road_2', 'assets/imported/environment/road_2.png');
    IMPORTED_KEYS.environment.push('imp_env_road_2');
    scene.load.image('imp_env_road_20', 'assets/imported/environment/road_20.png');
    IMPORTED_KEYS.environment.push('imp_env_road_20');
    scene.load.image('imp_env_road_21', 'assets/imported/environment/road_21.png');
    IMPORTED_KEYS.environment.push('imp_env_road_21');
    scene.load.image('imp_env_road_22', 'assets/imported/environment/road_22.png');
    IMPORTED_KEYS.environment.push('imp_env_road_22');
    scene.load.image('imp_env_road_23', 'assets/imported/environment/road_23.png');
    IMPORTED_KEYS.environment.push('imp_env_road_23');
    scene.load.image('imp_env_road_24', 'assets/imported/environment/road_24.png');
    IMPORTED_KEYS.environment.push('imp_env_road_24');
    scene.load.image('imp_env_road_25', 'assets/imported/environment/road_25.png');
    IMPORTED_KEYS.environment.push('imp_env_road_25');
    scene.load.image('imp_env_road_26', 'assets/imported/environment/road_26.png');
    IMPORTED_KEYS.environment.push('imp_env_road_26');
    scene.load.image('imp_env_road_3', 'assets/imported/environment/road_3.png');
    IMPORTED_KEYS.environment.push('imp_env_road_3');
    scene.load.image('imp_env_road_4', 'assets/imported/environment/road_4.png');
    IMPORTED_KEYS.environment.push('imp_env_road_4');
    scene.load.image('imp_env_road_5', 'assets/imported/environment/road_5.png');
    IMPORTED_KEYS.environment.push('imp_env_road_5');
    scene.load.image('imp_env_road_6', 'assets/imported/environment/road_6.png');
    IMPORTED_KEYS.environment.push('imp_env_road_6');
    scene.load.image('imp_env_road_7', 'assets/imported/environment/road_7.png');
    IMPORTED_KEYS.environment.push('imp_env_road_7');
    scene.load.image('imp_env_road_8', 'assets/imported/environment/road_8.png');
    IMPORTED_KEYS.environment.push('imp_env_road_8');
    scene.load.image('imp_env_road_9', 'assets/imported/environment/road_9.png');
    IMPORTED_KEYS.environment.push('imp_env_road_9');
    scene.load.image('imp_env_spots_2', 'assets/imported/environment/spots (2).png');
    IMPORTED_KEYS.environment.push('imp_env_spots_2');
    scene.load.image('imp_env_spots', 'assets/imported/environment/spots.png');
    IMPORTED_KEYS.environment.push('imp_env_spots');
    scene.load.image('imp_env_stones_1', 'assets/imported/environment/stones_1.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_1');
    scene.load.image('imp_env_stones_10', 'assets/imported/environment/stones_10.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_10');
    scene.load.image('imp_env_stones_11', 'assets/imported/environment/stones_11.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_11');
    scene.load.image('imp_env_stones_12', 'assets/imported/environment/stones_12.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_12');
    scene.load.image('imp_env_stones_2', 'assets/imported/environment/stones_2.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_2');
    scene.load.image('imp_env_stones_3', 'assets/imported/environment/stones_3.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_3');
    scene.load.image('imp_env_stones_4', 'assets/imported/environment/stones_4.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_4');
    scene.load.image('imp_env_stones_5', 'assets/imported/environment/stones_5.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_5');
    scene.load.image('imp_env_stones_6', 'assets/imported/environment/stones_6.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_6');
    scene.load.image('imp_env_stones_7', 'assets/imported/environment/stones_7.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_7');
    scene.load.image('imp_env_stones_8', 'assets/imported/environment/stones_8.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_8');
    scene.load.image('imp_env_stones_9', 'assets/imported/environment/stones_9.png');
    IMPORTED_KEYS.environment.push('imp_env_stones_9');
    scene.load.image('imp_env_tree_1', 'assets/imported/environment/tree_1.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_1');
    scene.load.image('imp_env_tree_2', 'assets/imported/environment/tree_2.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_2');
    scene.load.image('imp_env_tree_3', 'assets/imported/environment/tree_3.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_3');
    scene.load.image('imp_env_tree_4', 'assets/imported/environment/tree_4.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_4');
    scene.load.image('imp_env_tree_5', 'assets/imported/environment/tree_5.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_5');
    scene.load.image('imp_env_tree_6', 'assets/imported/environment/tree_6.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_6');
    scene.load.image('imp_env_tree_7', 'assets/imported/environment/tree_7.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_7');
    scene.load.image('imp_env_tree_8', 'assets/imported/environment/tree_8.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_8');
    scene.load.image('imp_env_tree_9', 'assets/imported/environment/tree_9.png');
    IMPORTED_KEYS.environment.push('imp_env_tree_9');
  }
};
